### ISSUE TITLE
Add elements level to extern shared memory calculation

### ISSUE THREAD

**Issue by erikzenker** [ComputationalRadiationPhysics/alpaka#110]
The interface to calculate the amount of extern shared memory only provides the blockExtent:

                ALPAKA_NO_HOST_ACC_WARNING
                       template<
                        typename TDim,
                        typename... TArgs>
                    ALPAKA_FN_HOST_ACC static auto getBlockSharedExternMemSizeBytes(
                        Vec<TDim, size::Size<TAcc>> const & blockElemExtent,
                        TArgs const & ... args)
                    -> size::Size<TAcc>
                    {
                        boost::ignore_unused(blockElemExtent);
                        boost::ignore_unused(args...);
    
                            return 0;
                    }

But this shared memory could also be depdendent on the element level.

**Comment by BenjaminW3** [comment]
It is already included because the parameter `blockElemExtent` because this is the product of the `blockThreadExtent` extent and the `threadElemExtent`.
Currently there has not been a reason to deliver both values independently.

**Comment by erikzenker** [comment]
Well, then that was not clear for me from the documentation. I will try to write an example for shared memory to make that more clear.

**Comment by psychocoderHPC** [comment]
I reopened this issue.

The reason for this is that we need to split the number of threads and elements. The point for this is that the amount of needed shared memory depends on the user algorithm. The given index domain (threads and elements per thread) are independent to the data.

e.g.
A user started a block with (32 threads and 4 elements per threads). The needed shared memory per thread for the user algorithm is 32 integer per block. The mapping from elements per thread to the shared memory e.g. means that each thread do four calculations on the same data in the shared memory. 

This can't be described if the trait `getBlockSharedExternMemSizeBytes` already multiply `blockThreadExtent` and `threadElemExtent`.

**Comment by psychocoderHPC** [comment]
solved with #121
