### ISSUE TITLE
vectorAdd with CUDA: Assertion failed

### ISSUE THREAD

**Issue by tu-maurice** [ComputationalRadiationPhysics/alpaka#111]
Due to a project assigment by Mr. Bussmann, my collegue and I need to use the Alpaka library on the Taurus of the TUD. Today I used the example program vectorAdd in the develop as well as the master branch to test if I can get Alpaka to run on the Taurus.

Unfortunately I get an Assertion Error whenever either version uses the GPU.
```
// develop branch. Should be similar to the one from the master branch (see attachments)
vectorAdd: /home/s7745593/alpaka/include/alpaka/exec/ExecGpuCudaRt.hpp:471: static void 
alpaka::stream::traits::Enqueue<alpaka::stream::StreamCudaRtSync, 
alpaka::exec::ExecGpuCudaRt<TDim, TSize, TKernelFnObj, TArgs ...>, 
void>::enqueue(alpaka::stream::StreamCudaRtSync&, const alpaka::exec::ExecGpuCudaRt<TDim, 
TSize, TKernelFnObj, TArgs ...>&) [with TDim = std::integral_constant<long unsigned int, 1ul>; TSize = 
long unsigned int; TKernelFnObj = VectorAddKernel; TArgs = {float*, float*, float*, long unsigned int}]: 
Assertion `threadElemExtent[TDim::value-1u-i] == 1' failed.
```
I'm not sure if the assertion failed because of an error in the example or if the assertion is wrong.

To run the vectorAdd example of the develop branch on the GPU, I applied some changes to the main.cpp (a diff is attached).

The environment we used to run this example:
```
Compiler    : gcc 4.9.1 (No gcc 4.9.2 available, might also be the cause of the problem)
Boost       : 1.56
Boost Fiber : N/A
CUDA        : 7.0.28
CMake       : 3.3
```

I tried to gather as much information as possible so here it is:
[develop-stderr.txt](https://github.com/ComputationalRadiationPhysics/alpaka/files/54224/develop-stderr.txt) - Error of vectorAdd in the develop branch
[develop-stdout.txt](https://github.com/ComputationalRadiationPhysics/alpaka/files/54227/develop-stdout.txt) - Output of vectorAdd in develop branch
[develop-main.cpp.txt](https://github.com/ComputationalRadiationPhysics/alpaka/files/54222/develop-main.cpp.txt) - "diff" between the repo version and "my" version of vectorAdd/src/main.cpp to run the Kernel on the GPU
[master-stdout.txt](https://github.com/ComputationalRadiationPhysics/alpaka/files/54220/master-stdout.txt) - Output of vectorAdd in the master branch
[master-stderr.txt](https://github.com/ComputationalRadiationPhysics/alpaka/files/54221/master-stderr.txt) - Error of vectorAdd in the master branch
[develop-CMakeCache.txt](https://github.com/ComputationalRadiationPhysics/alpaka/files/54219/develop-CMakeCache.txt) - CMakeCache.txt with information about the environment
[environment.txt](https://github.com/ComputationalRadiationPhysics/alpaka/files/54225/environment.txt) - summary of the CMakeCache.txt

**Comment by erikzenker** [comment]
Hi @tu-maurice,

I can reproduce your runtime assertion and will have a look at it. As long as there is 
a problem with the GPU accelerator you can the CPU accelerator. But I think we will
fix that issue soon. 

Thank you for telling us !

**Comment by erikzenker** [comment]
After having a look at the source code I found the problem. The GPU accelerator seems to assert that the element layer has an extent of one in all dimensions. It can be fixed by changing from `3u` to `1u` on this [line](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/example/vectorAdd/src/main.cpp#L121). A fix will follow tomorrow. The element layer tells the kernel how many elements should be processes per thread. Thus, a CPU accelerator can loop over these elements and use vectorization and caching effects. Usually, a GPU is not able to vectorize and therefore a element layers does not make sense there.

@BenjaminW3 is there a special reason why this asserted for the GPU accelerator ? 

PS: I would suggest you to work on the develop branch, since, this branch provides the most up to date examples and features.

**Comment by tu-maurice** [comment]
Thanks. I will try that temporary fix tomorrow morning.

And yes Mr. Bussmann told us to use the develop branch for our project but as the examples in the develop branch only one accelerator and I wanted to test several in one go, I used the master branch version to see if all of them work. When I got the error I tried the develop branch version next before creating an issue.

**Comment by erikzenker** [comment]
The old examples were moved to the integration tests in the develop branch e.g. [vectorAdd(axpy)](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/test/integ/axpy/src/main.cpp), because they were to complex for beginners. But, these test also be used as examples :honeybee:

**Comment by tu-maurice** [comment]
Too complex for alpaka beginners or too complex for c++11 beginners? :tulip:

**Comment by erikzenker** [comment]
Hrhr good question, I wonder what Bjarne Stroustrup would say ^^

**Comment by erikzenker** [comment]
The pull request #112 solved your issue and is now merged into the develop branch. It should now
be possible to compute more than one element per GPU thread.

**Comment by BenjaminW3** [comment]
The missing CI runtime tests for CUDA have hidden this bug.

**Comment by tu-maurice** [comment]
@erikzenker nice. thanks :+1: 
@BenjaminW3 Happens :smiley:
