### ISSUE TITLE
Example VectorAdd :unsigned leads to wrong calculation

### ISSUE THREAD

**Issue by vincentridder** [ComputationalRadiationPhysics/alpaka#129]
https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/examples/vectorAdd/src/main.cpp#L74
is always zero.
so the last thread will run out of bounds.

**Comment by tu-maurice** [comment]
Correction: The min() always returns zero because both parameters are unsigned.

**Comment by BenjaminW3** [comment]
I do not know how why this `static_cast` was necessary but you are right, it is wrong.
The code where this example was copied from does not have these `static_cast`.

The `static_cast` of a negative integral value to an unsigned integral type leads to a very large positive value. The minimum of this large value and zero is always zero.
The last thread will then try to calculate `(n/threads)-0` elements which is possibly out of bounds.

**Comment by tu-maurice** [comment]
@BenjaminW3 thank you.
