### ISSUE TITLE
out of memory access

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#135]
The method [pitchedOffsetBytesDim](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/mem/view/ViewSubView.hpp#L398) of `ViewSubView` results in a out of memory access if `Tidx` is equal than the `Tdim-1` of the view.

The issue is triggered by `Tidx + 1` in `mem::view::getPitchBytes<Tidx + 1u>(view);`

**Comment by psychocoderHPC** [comment]
Maybe we can remove this function because is is not used.

@BenjaminW3 Could you shortly explain what this method should do?

**Comment by BenjaminW3** [comment]
First of all [this line](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/mem/view/ViewSubView.hpp#L353) is wrong, there is one `view` argument too much.

Why should there be a out of memory access? `mem::view::getPitchBytes<TDim + 1u>(view);` should always return `1` for all types.

**Comment by psychocoderHPC** [comment]
If someonecalled [pitchedOffsetBytesDim](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/mem/view/ViewSubView.hpp#L392) with `Tidx = 1` on a 3 dimensional view than `Tidx + 1` = `2` is used to call `mem::view::getPitchBytes<2>()`. 
I think this is currently not the case bug it can be used wrong.

**Comment by BenjaminW3** [comment]
I was able to reproduce a memory access error. I will provide a fix and a unit test veryfying it within the next days.

**Comment by psychocoderHPC** [comment]
Big thanks. @erikzenker and me will look to the other issues.

**Comment by BenjaminW3** [comment]
The only open issue is #138 because #135, #136,#137 and #141 are all solved by my test.

**Comment by BenjaminW3** [comment]
`pitchedOffsetBytesDim` is a private class method which is called with the correct indices since #143.
