### ISSUE TITLE
`getPitchedBytes` for non x dimension is wrong

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#137]
The default implementation of the trait [GetPitchedBytes](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/mem/view/Traits.hpp#L76-L90) is wrong.
In the case we had a buffer or view (with extent [1000,100,10]) which has three dimensions and we call `getPitchBytes<0>(buff)` the default implementation used the extents to calculate this pitch.

Current implementation calculated: `extent of X` * `extent of Y` * `sizeof(element type)`
but should be
`getPitchBytes<of X>` *  `extent of Y`

@BenjaminW3: Could you please look over.

**Comment by BenjaminW3** [comment]
I do not fully see what you mean.
The documentation curently says `This is the distance in bytes in the linear memory between two consecutive elements in the next higher dimension (TIdx+1).` This should correctly be `TIdx-1`.

The only thing `getPitchBytes<0>(buff)` does is to calculate the full buffer size including all strides.

What do you mean by `getPitchBytes<of X>`? `X == 2` in the 3D case. So this returns the pitch between two rows (two consecutive elements in the Y dimension) which would be just `extent of X * sizeof(elem)`.

The only problem case I see is the following:
 * we have F dimensions
 * a user has specialized `getPitchBytes<F-1>` but not `getPitchBytes<F-2>`
 * someone calls `getPitchBytes<F-2>`. The default would ignore the Pitch in dimension F-1 and would incorrectly just take the extent of dimension F-1.

I will fix this case.

**Comment by erikzenker** [comment]
Fixed by #143
