### ISSUE TITLE
`copy` and `set` of views are boken

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#138]
If someone copies a view of a three dimensional buffer to another one than the wrong extents/ piches are used for the operation.
The some problem is alive for the operation `set`.

e.g. The [cuda operation set](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/mem/buf/cuda/Set.hpp#L440) is an good example 
The trait `extent::getHeight()` [here](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/mem/buf/cuda/Set.hpp#L461) results the height of the a view and not of the physical  memory behind the view. This results in a problem that the wrong height [here](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/mem/buf/cuda/Set.hpp#L480) is given to the cuda copy.
The some issue exists in the [cpu implementation](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/mem/buf/cpu/Set.hpp#L99)

The reason for that issue is that we not differ between physical memory extents and view extents.

@erikzenker is writing a test case for that problem

**Comment by BenjaminW3** [comment]
Is this only true for 3-dimensional views?

**Comment by psychocoderHPC** [comment]
A possible solution is to use the trait `getPitchedBytes<>` and calculate of of the pitch the physical memory sizes. 

e.g.
```C++
auto phyHeight = view::getPitchedBytes<1>/view::getPitchedBytes<2>;
```
but issue #135 and #134 must solved before.

Nevertheless the usage of this magic is not good IMO a better way is to add a trait `getPhysicalExtent` which should defined as the extents of the physical memory in the deepest parent view (the buffer or `ViewPlainPtrView`)

@BenjaminW3 Could you please participate

**Comment by BenjaminW3** [comment]
I will have a look over all of those issues.

**Comment by psychocoderHPC** [comment]
There is no need that you fix all of this, we will involve to be sure that we not interpret something wrong or misunderstood something.

**Comment by BenjaminW3** [comment]
`mem::view::getPitchBytes` always returns the pitch of the physical underlying buffer irrespective of the number of views stacked on top. If this is not the case there might be a bug (as #137 shows, there is one).

**Comment by erikzenker** [comment]
Currently, I am working on a fix for the cpu.

**Comment by erikzenker** [comment]
I also wrote a fix for the the cpu Set

**Comment by erikzenker** [comment]
I think, that we can not close that issue as long as the cuda copy and set is not fixed. I am on it !

**Comment by BenjaminW3** [comment]
Ah, ok. I have missed this.
