### ISSUE TITLE
No math on cuda?

### ISSUE THREAD

**Issue by tu-maurice** [ComputationalRadiationPhysics/alpaka#139]
I just ran into an error with alpaka::math::rsqrt which only occurs on cuda. After looking at the source code for rsqrt I saw an ALPAKA_FN_ACC_NO_CUDA in the file [RsqrtCudaBuiltIn.hpp:63](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/math/rsqrt/RsqrtCudaBuiltIn.hpp#L63).
Correct me if I'm wrong here but I'm pretty sure that's supposed to be ALPAKA_FN_ACC_CUDA_ONLY?

**Comment by BenjaminW3** [comment]
That is wrong. Could you please create a Pull Request using `ALPAKA_FN_ACC_CUDA_ONLY` instead? It would be even better, if you could look at all the other CUDA math functions as well ;-)

**Comment by tu-maurice** [comment]
Will do.
