### ISSUE TITLE
getPitchBytes for all dimensions

### ISSUE THREAD

**Issue by erikzenker** [ComputationalRadiationPhysics/alpaka#153]
This is a question issue:

I really would like to retrieve the pitches in all dimensions with a single functions call like:

    alpaka::Vec<Dim, Size> pitches(alpaka::mem::view::getPitchBytesAllDim(view));

I know that I can retrieve the pitchBytes for a single dimension, but is there
already some functionality to get it for all dimensions ?

**Comment by BenjaminW3** [comment]
It think `mem::view::getPitchBytesVec` should be what you are searching for.

**Comment by erikzenker** [comment]
Ahhh found it, thx !
