### ISSUE TITLE
Support for PowerPC in SysInfo.hpp

### ISSUE THREAD

**Issue by erikzenker** [ComputationalRadiationPhysics/alpaka#168]
The current implementation does only support the x86 architecture (see [here](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/dev/cpu/SysInfo.hpp#L58)).
We should add a case for `BOOST_ARCH_PPC` to be able the use the cpu accelerators on the
power pc architecture.

**Comment by BenjaminW3** [comment]
As far as I can see, the only thing that does not work on Power PC is the extraction of the CPU name which is only optional. There should not be anything preventing you to use alpaka on PowerPC.
The `cpuid` methods are x86 only and can therefore not be used on Power PC to get the CPU name.

**Comment by erikzenker** [comment]
I think we have to move this [line](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/dev/cpu/SysInfo.hpp#L58) after the `namespace detail {`. The rest should be fine.

**Comment by BenjaminW3** [comment]
Yes, this is a bug that is too easy to oversee. Could you please create a Pull Request?

**Comment by erikzenker** [comment]
I will provide the PR tomorrow morning, have a nice sunday evening :smiley:

**Comment by BenjaminW3** [comment]
Fixed in #170.
