### ISSUE TITLE
alpaka no allows to allocate 0 byte

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#182]
Is it necessary that alpaka not allow to allocate zero byte?
 - zero byte allocations are disallowed by [this](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/mem/buf/BufCudaRt.hpp#L393) asserts
Also to free a NULL pointer is not allowed. (https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/mem/buf/BufCudaRt.hpp#L109)

[This source](http://stackoverflow.com/a/4133555) points to the C++ standard which explicit allowes zero byte allocations.
This (source)[http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8] say that free of a NULL pointer is allowed.

@BenjaminW3 Did I miss something that avoid use to remove the asserts and allow zero byte allocations?

**Comment by BenjaminW3** [comment]
Yes, allocating zero size buffers and freeing a nullptr are both valid.
I do not see a reason for the assertions. I may have added them because such a usage is an indication of a bug in most cases (double free, wrong buffer size, etc...).
I will remove those assertions.

**Comment by psychocoderHPC** [comment]
thx for this fast answer!

I can remove this, because if we remove this we need to disallow NULL pointer pinning in the cuda back-end. 
My inspiration for this question was to avoid double work if there is a reason for this asserts.

I create a pull request next week.
