### ISSUE TITLE
Support for Library Builds

### ISSUE THREAD

**Issue by mxmlnkn** [ComputationalRadiationPhysics/alpaka#183]
[imresh](https://github.com/ComputationalRadiationPhysics/imresh) makes heavy use of interim static libraries to reduce compile times and also the finished product is supposed to be a [shared] library which can be linked against. There are some things which are problematic when using alpaka. I'm not finished porting yet, so there may be still more problems:

 - ~~`ALPAKA_FN_ACC` which e.g. replaces `__global__` when porting from CUDA adds a `__force_inline__` or `inline` which makes it impossible to compile a library, see commit 0564c8428bb9cfb2fb43b1d21770cee630464a1c~~ fixed in #194
 - to compile a library in the first place explicit instantiations of the accelerator type are necessary and add boiler plate could, which maybe could be prevented with some kind of macro provided by alpaka, see [here](https://github.com/ComputationalRadiationPhysics/imresh/commit/fa703de79a3501d8c119bc23976be61561405799#diff-3bf5faeb9a2e700f0ac9de222a9fbeb4R404) and [here](https://github.com/ComputationalRadiationPhysics/imresh/blob/fa703de79a3501d8c119bc23976be61561405799/src/imresh/libs/alpaka_T_ACC.hpp)  They were necessary anyway in imresh, but now they become nested.
 - ~~I couldn't find a `ALPAKA_ADD_LIBRARY` `CMake` function, only `ALPAKA_ADD_EXECUTABLE`, see commit 67e9554158212e76a895ba135b20feb1c7768f28~~ added in #184

**Comment by BenjaminW3** [comment]
You are talking about multiple issues, therefore I will start adressing the last one.
Issue #64 already mentions the missing support for `ALPAKA_ADD_LIBRARY`.
Your implementation can be merged into alpaka after adding the new CMake file to [this line](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/alpakaConfig.cmake#L363). Could you please create a Pull Request?

**Comment by BenjaminW3** [comment]
To adress your first point: I do not remember any strict reason for the `__forceinline__` and `inline` declarations. They are only there because the [original libPMacc declarations](https://github.com/ComputationalRadiationPhysics/picongpu/blob/release-0.1.2/src/libPMacc/include/types.h#L59-L61) used them. Maybe @psychocoderHPC knows more about the reasoning behind those.
I can imagine some performance advantages with those declarations, but without reliable tests showing this, I would agree to remove them.

**Comment by mxmlnkn** [comment]
A new problem after actually trying to compile and actually link one of the many tests of imresh with the OpenMP accelerator:

    [  7%] Built target alpaka
    [ 42%] Built target imresh
    [ 46%] Built target benchmark
    [ 50%] Built target cupla
    [ 73%] Built target examples
    [ 92%] Built target tests
    [ 96%] Linking CXX executable mainTestAll
    libtests.a(testVectorReduce.cpp.o): In function `alpaka::omp::getMaxOmpThreads()':
    ./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: multiple definition of `alpaka::omp::getMaxOmpThreads()'
    libtests.a(testVectorElementwise.cpp.o):./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: first defined here
    libimresh.a(vectorReduce.cpp.o): In function `alpaka::omp::getMaxOmpThreads()':
    ./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: multiple definition of `alpaka::omp::getMaxOmpThreads()'
    libtests.a(testVectorElementwise.cpp.o):./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: first defined here
    libimresh.a(cudacommon.cpp.o): In function `alpaka::omp::getMaxOmpThreads()':
    ./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: multiple definition of `alpaka::omp::getMaxOmpThreads()'
    libtests.a(testVectorElementwise.cpp.o):./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: first defined here
    libimresh.a(common.cpp.o): In function `alpaka::omp::getMaxOmpThreads()':
    ./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: multiple definition of `alpaka::omp::getMaxOmpThreads()'
    libtests.a(testVectorElementwise.cpp.o):./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: first defined here
    libimresh.a(memory.cpp.o): In function `alpaka::omp::getMaxOmpThreads()':
    ./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: multiple definition of `alpaka::omp::getMaxOmpThreads()'
    libtests.a(testVectorElementwise.cpp.o):./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: first defined here
    libimresh.a(stream.cpp.o): In function `alpaka::omp::getMaxOmpThreads()':
    ./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: multiple definition of `alpaka::omp::getMaxOmpThreads()'
    libtests.a(testVectorElementwise.cpp.o):./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: first defined here
    libimresh.a(device.cpp.o): In function `std::_Sp_counted_ptr_inplace<alpaka::dev::cpu::detail::DevCpuImpl, std::allocator<alpaka::dev::cpu::detail::DevCpuImpl>, (__gnu_cxx::_Lock_policy)2>::~_Sp_counted_ptr_inplace()':
    ./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: multiple definition of `alpaka::omp::getMaxOmpThreads()'
    libtests.a(testVectorElementwise.cpp.o):./imresh/cupla/alpaka/include/alpaka/core/OpenMp.hpp:39: first defined here

I think this is only the tip of the iceberg, because there are tens of function declarations inside headers in alpaka. I don't see anything against getting this to work though by splitting it into `.cpp` and `.hpp` except maybe, that it adds plenty of boiler plate code.


With `make VERBOSE=1` the command line with that problem is:

    /usr/bin/g++-4.9   -O2 -Wall -Wextra -Wunused-parameter -g -fopenmp   CMakeFiles/mainTestAll.dir/tests/mainTestAll.cpp.o  -o mainTestAll -rdynamic libimresh.a libtests.a libbenchmark.a libexamples.a libimresh.a -fopenmp -lpthread -lrt

Interesting to note here is that `libalpaka.a`, although compiled, isn't linked together here. After everything has been moved to `.cpp` files, `libalpaka.a` should maybe be automatically be added by `alpaka_add_executable`

**Comment by BenjaminW3** [comment]
I will have a look at those multiply defined symbols. I will look for a different solution instead of compiling seperate `.cpp` files to keep the library header only.
`libalpaka.a` is not currently linked because it does not contain anything at the moment as it is an empty dummy library necessary to trick CMake.

**Comment by psychocoderHPC** [comment]
Note: I tested in the past to create a static library for `cupla` similar than `libalpaka.a` but with content and afterwards link this to the user code. The static library was created every time the the user compiles his program.
This could be a solution for this issue. The problem with hat was something with the nvcc compiler. I can try it again and post more details.

**Comment by mxmlnkn** [comment]
@psychocoderHPC That would help, maybe I can work around some of the problems. One problem I can think of right now though, is that it may get to work existing projects more easily, but it maybe makes a recompile of everything necessary.

The problem here is: What if I have 2 object to compile which both use alpaka and then I want to link both together. I always will have the problem of alpaka reincluding some declarations like `getMaxOmpThreads`. Even for declarations which are templated over e.g. the block size problems could appear of both object files use the same block size, and so on ... A recompile of alpaka for both compilations wouldn't help either, I think.

Maybe some really hacky object file scrubbing could be done with the linker via CMake :)? I mean, just remove multiple definitions and leave only one, hoping they are all identical anyway.

**Comment by BenjaminW3** [comment]
Your error with multiple definitions comes from your removal of the `inline` keywords. Which errors do you get when not removing the `inline`s? I have created Pull Request #194 where `inline` is only added to the necessary functions.

**Comment by mxmlnkn** [comment]
These are some errors I get (the latter is the one I actually meant in my initial post)

    ./imresh/src/imresh/algorithms/vectorReduce.tpp:244:12: error: duplicate 'inline'
         inline ALPAKA_FN_ACC_CUDA_ONLY uint32_t getLaneId( void )
                ^
    ./imresh/src/imresh/algorithms/vectorReduce.cpp:65:5: error: explicit instantiation shall not use 'inline' specifier [-fpermissive]
         ALPAKA_FN_ACC void cudaKernelCalculateHioError
         ^

Now when looking at this I'm actually quite surprised, that getLaneId didn't throw any compile errors :S. Maybe I deleted all calls therefore it was not needed and not compiled. Also inline ptxas would have thrown an error at a later compile stage, maybe that's why.

    inline ALPAKA_FN_ACC_CUDA_ONLY uint32_t getLaneId( void )
    {
        uint32_t id;
        asm("mov.u32 %0, %%laneid;" : "=r"(id));
        return id;
    }

**Comment by psychocoderHPC** [comment]
Please remove the keyword inline before your functions.
This is the reason for the error message.
Inline ptx is not supported but can used for a xuda specialisation.

**Comment by mxmlnkn** [comment]
@psychocoderHPC I know, but this is only the first error, the second is more interesting. Although the first error adds another layer of complexity when porting, which then should be explained in the cupla `README.md`. Anyway, I don't think it's good style to enforce inlining

About the second error: I thought of a fun workaround. Enclose the explicit template instantiation with

    #define inline
    ...
    #undef inline

Hell, even something like this works:

    template
    #define inline
    ALPAKA_FN_ACC
    #undef inline
    void
    cudaKernelCopyToRealPart<cufftComplex,float>
    ::template operator()<T_ACC>
    (
        T_ACC const & acc,
        cufftComplex * const rTargetComplexArray,
        float * const rSourceRealArray,
        unsigned int const rnElements
    ) const;

**Comment by mxmlnkn** [comment]
First test compiles, links and runs now without `multiple definition` error, using OpenMP. There are still several problems with the CUDA version, though:

    ./imresh/cupla/alpaka/include/alpaka/workdiv/Traits.hpp(71): error: calling a __device__ function("getWorkDiv") from a __host__ __device__ function("getWorkDiv") is not allowed

**Comment by psychocoderHPC** [comment]
There is an issue for this #73. If you remove `__host__` in `ALPAKA_FN_ACC_HOST` all should be work fine. We working on a clean solution for this.

**Comment by mxmlnkn** [comment]
If I do that (and note, that it's `ALPAKA_FN_HOST_ACC`) I get:

    ./imresh/cupla/alpaka/include/alpaka/kernel/Traits.hpp(107): error: calling 
    a __host__ function("alpaka::kernel::traits::BlockSharedMemDynSizeBytes<
    cupla::CuplaKernel<imresh::algorithms::cudaKernelComplexNormElementwise<
    float, cupla::float2> > , alpaka::acc::AccGpuCudaRt<std::integral_constant<
    unsigned long, (unsigned long)3ul> , unsigned int> , void> ::
    getBlockSharedMemDynSizeBytes<alpaka::Vec<std::integral_constant<
    unsigned long, (unsigned long)3ul> , unsigned int> , alpaka::Vec<
    std::integral_constant<unsigned long, (unsigned long)3ul> , unsigned int> ,
    float *, const cupla::float2 *, unsigned int > ") from a __device__ 
    function("alpaka::kernel::getBlockSharedMemDynSizeBytes<
    alpaka::acc::AccGpuCudaRt<std::integral_constant<unsigned long, 
    (unsigned long)3ul> , unsigned int> , cupla::CuplaKernel<
    imresh::algorithms::cudaKernelComplexNormElementwise<float, cupla::float2> > 
    , std::integral_constant<unsigned long, (unsigned long)3ul> , float *, 
    const cupla::float2 *, unsigned int > ") is not allowed

**Comment by psychocoderHPC** [comment]
@mxmlnkn Sry my fault please remove `__host__` in `ALPAKA_FN_ACC` not in `ALPAKA_FN_ACC_HOST`

**Comment by BenjaminW3** [comment]
@mxmlnkn : Is there anything still missing for this issue to be closed? `ALPAKA_ADD_LIBRARY` has been added and the `inline` problem is solved now. The support for a CUDA only mode which would allow CUDA intrinsics and other CUDA code to be called is tracked in #73. Is there anything left?

**Comment by mxmlnkn** [comment]
I can't think of anything right now. imresh builds correct with alpaka commit bf76b7dd234e65308add339aa5e168d5d06a41d6 after the replacement
```shell
find ../src/ ../benchmark/ -name '*pp' -execdir sed -i 's|ALPAKA_FN_NO_INLINE|ALPAKA_FN|g' '{}' \;
```
