### ISSUE TITLE
Minimize alpaka build tests

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#192]
Is it possible to reduce the amount of travis-CI test?

Currently we check more than on `cmake`, `gcc` and `clang` version. 
The problem is that we can only run one test for the group `ComputationalRadiationPhysics`. If two alpaka tests are queued no other project of our group can be checked.

We should reduce the software combinations!

**Comment by BenjaminW3** [comment]
I will provide a Pull Request that reduces the number of builds.

**Comment by psychocoderHPC** [comment]
:+1:

**Comment by BenjaminW3** [comment]
The Pull Request is waiting to be built which shows us a different problem.
The load on Travis seems to be increasing more and more. Therefore, starting in the (middle european) afternoon, builds do not start immediately and are queued (sometimes for multiple hours). However, this can not be solved by us.

**Comment by BenjaminW3** [comment]
I will close this, as #193 reduced the build times on Travis CI by half.

**Comment by psychocoderHPC** [comment]
:+1:
