### ISSUE TITLE
Reference to already destroyed objects

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#197]
I ported PIConGPU with the help of cupla to alpaka and get a deadlock that a kernel never finished ( the event after the kernel is not triggered).
I am not 100% sure if this is an alpaka bug but I think so.

If I use `::alpaka::stream::StreamCpuAsync` and `::alpaka::acc::AccCpuOmp2Threads<>` I can trigger a deadlock in the most runs. With `::alpaka::stream::StreamCpuSync` the deadlock is never triggered.

I think the problem is trigger by some code part like [this](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/core/ConcurrentExecPool.hpp#L362) where a functor is created and some arguments are [bind as reference](http://de.cppreference.com/w/cpp/utility/functional/bind). If the functor which is created with bind is passed to a thread than it can be that the (internal stored) references are not valid anymore.
This can be the case if an alpaka kernel is created in a local scope and passed to `::alpaka::stream::enqueue()`

```C++
{
 MyKernel kernel;
 auto dev( manager::Device<AccDev>::get().current() );
  ::alpaka::workdiv::WorkDivMembers<
    KernelDim,
    IdxType
  > workDiv(
      static_cast<IdxVec3>(gridSize),
      static_cast<IdxVec3>(blockSize),
      static_cast<IdxVec3>(elemPerThread)
  );
  auto const exec(::alpaka::exec::create<Acc>(workDiv, kernel, args...));
  ::alpaka::stream::enqueue(stream, exec);
} // kernel, workDiv and args are now destroyed and get invalid if references are used in a different thread which is already running
```

@BenjaminW3 Currently I can't find the place were we must definitely create a copy of the kernel and the given parameter to avoid that references are stored in [TaskPackages](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/core/ConcurrentExecPool.hpp#L107). If my description of the problem is not clear enough could you please call me by phone (at work). I need some help to locate the broken code part.

**Comment by BenjaminW3** [comment]
Could you try to remove the wrapping `std::forward`s from (this line)[https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/core/ConcurrentExecPool.hpp#L362]?
This might not be enough but it is a first try.

Do you have a minimal reproducible example?

**Comment by psychocoderHPC** [comment]
I tried to remove `std::forward` in the marked line but it deadlocked.

I can't provide a minimal example. The problem is that it is very hard to get an example for a deadlock. 
Currently it is only assumption that `std::forward` creates this error.

**Comment by psychocoderHPC** [comment]
I tested the cuda accelerator and can't produce the deadlock with cuda.

**Comment by BenjaminW3** [comment]
Have you tried using valgrind or clang ASAN? If an invalid refernce is accessed, there is most probably an invalid memory access.

**Comment by psychocoderHPC** [comment]
PIConGPU with alpaka is currently not tested with clan.
I will run valgrind again.

**Comment by psychocoderHPC** [comment]
It is not possible to run with valgrind to the point where the deadlock is showing up. Valgrind slows down the code to much :-(

**Comment by psychocoderHPC** [comment]
Note: I will check if I can reproduce the effect with our game of life example.

**Comment by psychocoderHPC** [comment]
It looks like I found the race condition bug. I run some tests to be sure and will push my results.
