### ISSUE TITLE
atomic operations with scope

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#201]
Based on the fact in #200 I realized that we need a scope to a alpaka layer for atomic operations where they are atomic.
Currently the atomic operations are very slow if they are emulated (e.g., with `omp  critical section`) this result in code which is not performance portable.
Alpaka knows best which layer (grid, block, thread) needs which type of atomics.

We should add to all alpaka atomics a hint from the user in which scope the operation must be atomic.

``` C++
::alpaka::atomic::atomicOp<::alpaka::atomic::op::Add>(acc, ppPointer, ppValue, ::alpaka::Threads )
```

Scopes can be:
alpaka::Threads - operation is atomic between threads in a block
alpaka::Blocks - operation is atomic between blocks in a grid
alpaka::Grids - operation is atomic between grids on a device

Why the scope should not be based on memory (e.g., shared memory, global memory)?
The reason is that global memory can used by the user in that way that the domains of the blocks are independent. With this strategy and if the user defines  that the scope is `::alpaka::Threads` the atomic inside alpaka can be `atomic::AtomicNoOp` if the accelerator is serialized on thread level ( e.g. in `AccCpuSerial`, `AccCpuOmp2Blocks`)

**Comment by psychocoderHPC** [comment]
I tested the difference of the current alpaka atomics compared to a hacked version of this issue.
The speedup with PIConGPU and `AccCpuOmp2Blocks` is `>10`

**Comment by erikzenker** [comment]
While porting HASEonGPU to alpaka is also noticed the bad runtime behaviour of alpaka atomics for omp based accelerators. I was able to reduce the number of atomics necessary such that the final performance was still acceptable. Nevertheless, I support this issue because the current implementation decreases atomic performance a lot.

**Comment by BenjaminW3** [comment]
Yes, this is a real issue and it is already documented within the OpenMP atomic [implementation](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/atomic/AtomicOmpCritSec.hpp#L95) itself. The same is also true for the version using `std::lock_guard<std::mutex>`.
How do you think this could be implemented generally? Do you want this parameter to be optional or required (or maybe as template parameter)?

**Comment by psychocoderHPC** [comment]
We can add a optional parameter which is by default set to `alpaka::Grids` which is save in all cases and the slowest version (on the most accelerators). If the user set the parameter explicit the implementation dependent to the accelerator is used.
I can create a pull request after the GTC2016 and we can discuss later on based on the pull request.
