### ISSUE TITLE
EventCpu.hpp:284:32: warning: declaration of ‘lk’ shadows a previous local [-Wshadow]

### ISSUE THREAD

**Issue by mxmlnkn** [ComputationalRadiationPhysics/alpaka#203]
```
alpaka/include/alpaka/event/EventCpu.hpp:284:32: warning: declaration of ‘lk’ shadows a previous local [-Wshadow]
                                 std::lock_guard<std::mutex> lk(spEventCpuImpl->m_Mutex);
                                ^
alpaka/include/alpaka/event/EventCpu.hpp:248:30: note: shadowed declaration is here
                     std::lock_guard<std::mutex> lk(spEventCpuImpl->m_Mutex);
                              ^
```
As this gets repeated on every object compilation, I find it crucial to eliminate these warnings somehow, either through cmake or by renaming the second `lk` inside the lambda with `lk2` or some more meaningful name even.

**Comment by BenjaminW3** [comment]
Which compiler version do you use? I think the warning is not correct as the shadowing declaration is within a non-capturing lambda. Therefore the outer declaration should not be shadowed as it is not within the scope available from within the lambda. Nevertheless, I will rename it.

**Comment by mxmlnkn** [comment]
The warning appears with g++ 4.9.3, 5.3.1 and clang++ 3.6.4, see also [here](http://stackoverflow.com/questions/31390941/can-a-non-captured-variable-be-shadowed-by-a-lambda-parameter)
You assigned me for the pull request, but I don't have sufficient permissions for this repo to merge. The fix itself works.
