### ISSUE TITLE
Adding support for constant memory

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/alpaka#209]
I noticed with Isaac, that Cuda code with `__constant__` variables cannot be directly ported to Alpaka. Passing a const parameter to a kernel is slower than directly using `__constant__` variables.

So I would like to add a way for using `__constant__` variables with Alpaka. As `__constant__` variables cannot be member of a struct or class I would suggest to define a `#define` like `ALPAKA_CONST_VAR`, which resolves to `__constant__` for Cuda, but is empty for CPU accelerators. However I am not sure, how global variables on xeon phi devices work. Imho this should be considered before adding this feature.

Only the host can change the content of a `__constant__` variable in Cuda, either with copying from host to the variable (`cudaMemcpyToSymbol`) or directly from device memory to the constant memory (`cudaMemcpy`+ `cudaGetSymbolAddress`).

I am not sure, how to implement this best in an _Alpaka way_. Normally you would use `alpaka::mem::view::copy` for copying stuff. But as constant memory is very special, maybe a `alpaka::mem::const::copy` (which throughs exception if used in the wrong direction) would be more suitable?

So, please tell me your thoughts!

**Comment by BenjaminW3** [comment]
Not being able to have a `__constant__` variable as a member is a hard limitation.
Adding a `ALPAKA_VAR_CONST` defined to `__constant__` for CUDA seems to be the way to go (at a first look).
Please note that each device in a multi-GPU setup has a seperate instance of the `__constant__` memory. Therefore the copy needs to know the specific device.

I would suggest to create a method `alpaka::mem::const::getView(dev, ptr, extent)` which creates a `ViewConstVar` given the device, the constant variable pointer and its extent.
Internally it calls `cudaGetSymbolAddress` to get the pointer on the device.
Later on, this `ViewConstVar` can be used like any other view in a standard `alpaka::mem::view::copy` call that automatically calls the correct memcpy. This should even support inter-GPU `__constant__` memory copies.  

However, as you said, it would be preferable if someone could find out how something similar could work with offloaded OpenMP code or if this is not possible at all. As we do not support OpenMP offloading at the moment, this would not be a blocker.

**Comment by theZiz** [comment]
As I got a bit more spare time I had the possibility to think about this feature request. I think the most important thing you mentioned is, that every cuda device got it's own constant memory. So the same has to be the case for any other accelerator. I am right, that this is not a problem at all, as every not-gpu device count is hard coded to 1 atm?

So in fact somebody should be able to just implement it as suggested now?

**Comment by BenjaminW3** [comment]
At least I hope that my quick notes will work out in the end. Do you want to volunteer implementing it? I may or may not have time to do it myself but I can not promise anything.

**Comment by theZiz** [comment]
I doubt I will find time the next 2 weeks as ISAAC and the ISAAC plugin for PIConGPU need some very important polishings first, but after that I would try to do implement it myself (probably with the help of @erikzenker)

**Comment by BenjaminW3** [comment]
I have added a first prototype of this in #226. Could someone please test the correpsonding unit test on a CUDA device and test it in a real world scenario? I am not sure it will work at all.

**Comment by erikzenker** [comment]
I am going to evaluate the unit test.

**Comment by erikzenker** [comment]
Fixed by #226
