### ISSUE TITLE
Clang CUDA backend

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/alpaka#214]
It would be great if we could test the open source [clang 3.8+ CUDA](http://llvm.org/releases/3.8.0/tools/clang/docs/ReleaseNotes.html#cuda-support-in-clang) end-to-end compilation with our CUDA backend in our [compiler list](https://github.com/ComputationalRadiationPhysics/alpaka#supported-compilers) and report problems that occur to [`cfe-dev` list](http://lists.llvm.org/mailman/listinfo/cfe-dev).

**Comment by BenjaminW3** [comment]
There is already Pull Request #165 from me testing this configuration.
It is only a test branch and hacks in many things.
The biggest problems so far come from boost not supporting clang as a cuda compiler (see the first comment in the PR)
Any help is appreciated!

**Comment by ax3l** [comment]
should we report upstream with boost?
They document their tasks in [this trac](https://svn.boost.org/trac/) and do accept PRs on github.
