### ISSUE TITLE
CUDA & std::thread / Boost.Fiber

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/alpaka#215]
The note in the [compiler section](https://github.com/ComputationalRadiationPhysics/alpaka#supported-compilers)

> NOTE: :bangbang: Currently the CUDA accelerator back-end can not be enabled together with the std::thread accelerator back-end or the Boost.Fiber accelerator back-end due to bugs in the NVIDIA nvcc compiler :bangbang:

Should be documented in an issue (this one?) and reported upstream to Nvidia.
If already done so, please document the nvidia bug tracker number (and affected versions) here.

We can also send reproducable code to Nvidia (via mail) for testing against the upcoming and announced CUDA 8 release.

**Comment by BenjaminW3** [comment]
This has already been solved in CUDA 7.5. I am not sure anymore if it is even a problem anymore with CUDA 7.0 as this remark has not been part of the develop branch for a loooong time (The master branch is very old)

**Comment by BenjaminW3** [comment]
I have looked for the changes and it has already been solved.
We should provide a current master build soon.

**Comment by ax3l** [comment]
ah sorry, did only check `master`
