### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#233]
- [x] move and update the version number from `alpaka/include/alpaka/alpaka.hpp` to `alpaka/include/alpaka/version.hpp` and add an include to the new file into the former
- [x] test doxygen docu generation and fix documentation errors
- [x] merge develop to master
- [x] regenerate the doxygen docu and push it into the `gh-pages` branch as described in `alpaka/doc/dev/gh-pages.md`
- [x] tag the master commit with the release number e.g. `alpaka-0.1.0`
- [x] add a DOI
- [ ] Party :tada:

**Comment by psychocoderHPC** [comment]
We should use a file`version.hpp` to ship the version number like in [PIconGPU(https://github.com/ComputationalRadiationPhysics/picongpu/blob/release-0.1.2/src/picongpu/include/version.hpp)] or in [libsplash](https://github.com/ComputationalRadiationPhysics/libSplash/blob/master/src/include/splash/version.hpp)
The advantage is that it is clear where the number can be found and feature release number changes not change a file which has nothing to do with the release.

**Comment by BenjaminW3** [comment]
Yes, this is a good idea.

**Comment by erikzenker** [comment]
I create a version file and adapted the version recognition in the CMAKE config in #249

**Comment by erikzenker** [comment]
Merged dev into master

**Comment by BenjaminW3** [comment]
I will do the docu update.

**Comment by BenjaminW3** [comment]
Is there anything else to do for the release?
The final release tag is different from what I suggested above. Is there any reason to use one version above the other?

**Comment by psychocoderHPC** [comment]
@ax3l  and me released alpaka yesterday. (sry forgot to updte this issue)
We follow the naming schemes  which we used in our other softwares. 
If you mean why we skip the name `alpaka` as prefix of the version:
  - it is clear  for the user that the tag is part of alapka
  - if you download the tag as zip the name is changed to `alapka-0.1.0` by github
