### ISSUE TITLE
Warning and possible undefined behaviour if using alpaka::stream::enqueue with CUDA

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/alpaka#239]
I did some tests with the most recent Alpaka version and noticed with my project, that I got a warning about  `warning: calling a __host__ function from a __host__ __device__ function is not allowed`.

However using CUDA 7.5 with the provided examples I ran into the very same problem. Here is the output from compiling the most basic example `helloWorld.cpp`:

```
./alpaka/include/alpaka/block/shared/st/Traits.hpp(107): warning: calling a __host__ function from a __host__ __device__ function is not allowed
          detected during:
            instantiation of "auto alpaka::block::shared::st::freeMem(TBlockSharedMemSt &)->void [with TBlockSharedMemSt=alpaka::block::shared::st::BlockSharedMemStNoSync]" 
(171): here
            instantiation of "auto alpaka::block::shared::st::traits::FreeMem<TBlockSharedMemSt, std::enable_if<std::integral_constant<__nv_bool, <expression>>::value, void>::type>::freeMem(TBlockSharedMemSt &)->void [with TBlockSharedMemSt=alpaka::acc::AccCpuSerial<alpaka::dim::DimInt<3UL>, std::size_t>]" 
(107): here
            instantiation of "auto alpaka::block::shared::st::freeMem(TBlockSharedMemSt &)->void [with TBlockSharedMemSt=alpaka::acc::AccCpuSerial<alpaka::dim::DimInt<3UL>, std::size_t>]" 
./alpaka/include/alpaka/exec/ExecCpuSerial.hpp(173): here
            instantiation of "auto alpaka::exec::ExecCpuSerial<TDim, TSize, TKernelFnObj, TArgs...>::operator()() const->void [with TDim=alpaka::dim::DimInt<3UL>, TSize=std::size_t, TKernelFnObj=HelloWorldKernel, TArgs=<>]" 
./alpaka/include/alpaka/stream/StreamCpuSync.hpp(229): here
            instantiation of "auto alpaka::stream::traits::Enqueue<alpaka::stream::StreamCpuSync, TTask, void>::enqueue(alpaka::stream::StreamCpuSync &, const TTask &)->void [with TTask=alpaka::exec::Exec<alpaka::acc::AccCpuSerial<alpaka::dim::DimInt<3UL>, std::size_t>, HelloWorldKernel>]" 
./alpaka/include/alpaka/stream/Traits.hpp(80): here
            instantiation of "auto alpaka::stream::enqueue(TStream &, TTask &&)->void [with TStream=alpaka::stream::StreamCpuSync, TTask=const alpaka::exec::Exec<alpaka::acc::AccCpuSerial<alpaka::dim::DimInt<3UL>, std::size_t>, HelloWorldKernel> &]" 
./alpaka/example/helloWorld/src//helloWorld.cpp(208): here

./alpaka/include/alpaka/block/shared/st/BlockSharedMemStNoSync.hpp(127): warning: calling a __host__ function("std::vector<std::unique_ptr<unsigned char, boost::alignment::aligned_delete> , std::allocator<std::unique_ptr<unsigned char, boost::alignment::aligned_delete> > > ::clear") from a __host__ __device__ function("alpaka::block::shared::st::freeMem<alpaka::block::shared::st::BlockSharedMemStNoSync> ") is not allowed
```

I took a look in the file `StreamCpuSync.hpp`, where enqeue is defined, which is (naturally) a **ALPAKA_FN_HOST** function. The called ()operator in `ExecCpuSerial.hpp` is **ALPAKA_FN_HOST**, too. However the call `block::shared::st::freeMem(acc);` dissolves to the function `freeMem` in `Traits.hpp`, which is itself a **ALPAKA_FN_ACC**. So the compiler is right, this should not happen.

**Comment by theZiz** [comment]
I just noticed, the helloWorld example used `AccCpuSerial` and my example `AccCpuOmp2Blocks`. However if I used `AccGpuCudaRt` instead the warning disappeared. So most probaly no undefined behaviour as this warning has no meaning for application usinc nvcc, but not using the gpu at all.

**Comment by BenjaminW3** [comment]
As you have noticed, this only occurs in mixed mode, where nvcc compiles CPU and GPU code. However, this is expected and only nvcc produces those false positives. clang does not produce those warnings when natively compiling alpaka with CUDA support because we never actually call `__host__` only code in a `__device__` only code path.
