### ISSUE TITLE
Not building with boost 1.56

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/alpaka#241]
I just noticed, that when building alpaka with boost 1.56 many `error: "auto" function requires a trailing return type` errors are thrown, e.g. in `include/alpaka/mem/view/ViewPlainPtr.hpp` line 339.

Defining `BOOST_NO_CXX14_RETURN_TYPE_DEDUCTION` solves this, but it's quite a hacky solution.

**Comment by BenjaminW3** [comment]
As is written in the ReadMe, the develop branch is not compatible with boost < 1.59 but only with the current last 3 versions. Only the old master branch had support for boost 1.56.
`BOOST_NO_CXX14_RETURN_TYPE_DEDUCTION` is not the only problem as there have been CUDA problems with older versions especially in the unit tests.

**Comment by theZiz** [comment]
Oh, okay. But if this will stay this way, maybe the alpaka cmake config file should check for boost 1.59 instead of boost 1.56. ;) This is at least more obviuos than a ReadMe.

**Comment by BenjaminW3** [comment]
You are right, I will create a PR.
