### ISSUE TITLE
clang apt-repo offline

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#244]
The llvm apt-repository has been taken offline due to excessive load until a solution can be found.
So all the clang builds are currently failing.
See [here](http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html).
I have temporarily disabled the status check required before a merge, as all our Travis builds will be marked as failed as long as this has not been resolved and this would hinder us from merging anything for an unknown time.

**Comment by BenjaminW3** [comment]
The apt repo has temporarily been moved to [here](http://llvm-apt.ecranbleu.org/apt/). This would enable us to fix the CI temporarily.
I will not be able to test this until July.

**Comment by erikzenker** [comment]
Fixed temporarily by #245
