### ISSUE TITLE
add doxygen documentation to gh-pages

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#25]
Github allows to host webpages by using a `gh-pages` branch.
The generated doxygen documentation could be made available there.

See: https://github.com/smartell/APIDemo/tree/master
or: http://rickfoosusa.blogspot.de/2011/10/howto-use-doxygen-with-github.html

This could be enhanced even more by automatically regenerating and pushing the documentation by Travis CI.

**Comment by BenjaminW3** [comment]
Done! Manual update for now.

**Comment by ax3l** [comment]
ok, pls add at least a minimal script anyway - otherwise a mini documentation "how to update" would be necessary.

**Comment by BenjaminW3** [comment]
Oh sorry! I missed to add a note that this documentation is already available in `doc/dev/gh-pages.md`

**Comment by ax3l** [comment]
oh, great! :+1:

**Comment by ax3l** [comment]
just a minor hint: you can use more [code-highlighting](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) in your markdown files. that adds correct syntax highlighting :)
