### ISSUE TITLE
missing initializer

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#279]
This description was original opened by @mxmlnkn in the project [cupla](https://github.com/ComputationalRadiationPhysics/cupla) as issue https://github.com/ComputationalRadiationPhysics/cupla/issues/37

The warning is produced by `alpaka`.

```
cupla/alpaka/include/alpaka/mem/buf/cuda/Copy.hpp:638:51: warning: missing initializer for member ‘cudaMemcpy3DPeerParms::srcPos’ [-Wmissing-field-initializers]
                         cudaMemcpy3DPeerParms cudaMemCpy3DPeerParms = {0};
                                                   ^
cupla/alpaka/include/alpaka/mem/buf/cuda/Copy.hpp:638:51: warning: missing initializer for member ‘cudaMemcpy3DPeerParms::srcPtr’ [-Wmissing-field-initializers]
cupla/alpaka/include/alpaka/mem/buf/cuda/Copy.hpp:638:51: warning: missing initializer for member ‘cudaMemcpy3DPeerParms::srcDevice’ [-Wmissing-field-initializers]
cupla/alpaka/include/alpaka/mem/buf/cuda/Copy.hpp:638:51: warning: missing initializer for member ‘cudaMemcpy3DPeerParms::dstArray’ [-Wmissing-field-initializers]
cupla/alpaka/include/alpaka/mem/buf/cuda/Copy.hpp:638:51: warning: missing initializer for member ‘cudaMemcpy3DPeerParms::dstPos’ [-Wmissing-field-initializers]
cupla/alpaka/include/alpaka/mem/buf/cuda/Copy.hpp:638:51: warning: missing initializer for member ‘cudaMemcpy3DPeerParms::dstPtr’ [-Wmissing-field-initializers]
cupla/alpaka/include/alpaka/mem/buf/cuda/Copy.hpp:638:51: warning: missing initializer for member ‘cudaMemcpy3DPeerParms::dstDevice’ [-Wmissing-field-initializers]
cupla/alpaka/include/alpaka/mem/buf/cuda/Copy.hpp:638:51: warning: missing initializer for member ‘cudaMemcpy3DPeerParms::extent’ [-Wmissing-field-initializers]
```
The problem here is the `={0}` which only initializes the first member to 0, not sure what is wanted here though. Maybe no initializer list may be necessary, or a whole `memset( &cudaMemCpy3DPeerParms, 0, sizeof(cudaMemCpy3DPeerParms) )` is what is wanted here.

**Comment by BenjaminW3** [comment]
Could you please try what `={}`produces?

**Comment by BenjaminW3** [comment]
push

**Comment by psychocoderHPC** [comment]
I can try it but I think it can not work. This object is a C object and there is not constructor to initialize it with an emty list.

**Comment by psychocoderHPC** [comment]
I will do the test but currently there are some more important tasks on my todo list.

**Comment by ax3l** [comment]
Let me copy my comment from the `cupla` issue:

As a similar example, see https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.1.2/src/libPMacc/include/cuSTL/container/copier/Memcopy.hpp#L53-L54

You need to look up the according default values in the documentation of `cudaMemcpy3DPeerParms` and set them:
[Guide](http://docs.nvidia.com/cuda/cuda-runtime-api/structcudaMemcpy3DPeerParms.html) or doxygen [from GPUOcelot](http://gpuocelot.gatech.edu/doxygen/structcudaMemcpy3DPeerParms.html)
