### ISSUE TITLE
Intel compiler detection broken because of boost

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/alpaka#298]
Since you changed `__INTEL_COMPILER` for `BOOST_COMP_INTEL` (https://github.com/ComputationalRadiationPhysics/alpaka/commit/2e5854006c12fd703cb524bccdad1b04bf6cacc3) the intel compiler is not working anymore for Alpaka as `BOOST_COMP_INTEL` seems to be broken at least until boost 1.62.0 (bug report for boost itself will follow).

@psychocoderHPC and me investigated this bug and we discovered, that the macro is not defined properly. A work around is this code before the first alpaka include:
```C++
#include <boost/predef.h>
#if BOOST_COMP_INTEL == 0 // Work around for broken intel detection
    #if defined(__INTEL_COMPILER)
        #ifdef BOOST_COMP_INTEL_DETECTION
            #undef BOOST_COMP_INTEL_DETECTION
        #endif
        #define BOOST_COMP_INTEL_DETECTION BOOST_PREDEF_MAKE_10_VVRR(__INTEL_COMPILER)
        #if defined(BOOST_COMP_INTEL)
            #undef BOOST_COMP_INTEL
        #endif
        #define BOOST_COMP_INTEL BOOST_COMP_INTEL_DETECTION
    #endif
#endif
```
This tries to define `BOOST_COMP_INTEL` if it was not set yet, so if boost is fixed somewhen in the future the boost define is used. Beside making `BOOST_COMP_INTEL` usable, it also uses the correct versioning format VVRR for the intel compiler instead of VRP, which resulted in 5.0.0 for intel compiler version 15 instead of the correct 15.00

Now I wonder, where to add this work around. The possibilities I have in mind are:
* in the `alpaka.hpp` (maybe as extra include)
* as new file, but included in every file using `BOOST_COMP_INTEL` (`core/Vectorize.hpp`, `core/Unroll.hpp`, `/core/Debug.hpp`, `/core/Align.hpp`, `/vec/Vec.hpp`)

What do you think? I will create a pull requests if you decided the best way of adding the work around.

**Comment by BenjaminW3** [comment]
Thanks for investigating this bug!
You could add it in `core/Common.hpp` directly under `#include <boost/version.hpp>`. This file is included by every alpaka file.
However, please check for `#if BOOST_VERSION <= BOOST_VERSION_NUMBER(1, 63, 0)` before including `predef.h`.

**Comment by theZiz** [comment]
I thought about adding it there too, but `core/Debug.hpp` is even included before `boost/version.hpp` in `core/Common.hpp` and is using `BOOST_INTEL_COMP`, too. So the right place is probably even before including `core/Debug.hpp` or inside `core/Debug.hpp` itself although is does not really fit as this has nothing to do with debugging.

Why should I not include `predef.h` in Boost > 1.63?

**Comment by BenjaminW3** [comment]
Yes, you are right, Debug.hpp already includes `predef.h`. So this is not necessary.
Better add a NewFile `BoostPredefWorkaround.hpp` and include it at the top of `core/Debug.hpp`

**Comment by theZiz** [comment]
Will do so, but what about the include of `predef.h`after Boost 1.63?

**Comment by BenjaminW3** [comment]
This is no preoblem, as it is already included in every file due to `Debug.hpp` using it.
