### ISSUE TITLE
heap data alignment required

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#321]
To unleash the full performance of a processor we need to take care of the heap data alignments for global and shared memory.
Currently we align all dynamic allocated data with `boost::alignment::aligned_alloc(16u,...)`.
With 16 byte alignment we get in the most cases only SSE support from the compiler. To support authorized AVX, AVX2 and Phi KNL AVX2 code we need to check at compile time for the instruction set and used the corresponding alignment in `aligned_alloc(...)`

```
alignments needed
SSE = 16 byte
AVX/AVX2 = 32 byte
AVX-512 (Intel Phi KNL) = 64 byte
```

CC-ing: @theZiz

**Comment by BenjaminW3** [comment]
You may want to use the macros defined by Boost.Predef for this purpose see [here](http://www.boost.org/doc/libs/1_60_0/libs/predef/doc/html/predef/reference/boost_hw_hardware_macros.html).
It is currently missing support for detecting AVX-512.

You could use the macros manually as it is done in alpaka:
```
#if defined(__AVX512BW__)
                64u
#elif defined(__AVX2__)
                32u
#elif defined(__SSE2__)
                16u
#elif defined(__ARM_NEON__)
                16u
#elif defined(__ALTIVEC__)
                16u
...
#endif
```
