### ISSUE TITLE
ViewPlainPtr for const buffers

### ISSUE THREAD

**Issue by bertwesarg** [ComputationalRadiationPhysics/alpaka#337]
I would like to have a `ViewPlainPtr` to pass in `const` pointers. I know I can get a `const` pointer out, but that does not help me, if the input is alreay `const`.

Thanks.

**Comment by BenjaminW3** [comment]
I do not know your use-case, but you should be able to declare the `Elem` type as `const int` and it should work [see this example](https://github.com/ComputationalRadiationPhysics/alpaka/blob/5831770db2ababfb04030f7bc3fae0a19c097114/test/unit/mem/view/src/ViewStaticAccMem.cpp#L137-L138).

**Comment by bertwesarg** [comment]
Looks reasonable and it works. Thanks.
