### ISSUE TITLE
Example for a block of shared memory

### ISSUE THREAD

**Issue by SimeonEhrig** [ComputationalRadiationPhysics/alpaka#353]
Hello everybody,

I want to implement some algorithm with alpaka on the cuda backend. To improve the performance, I want to use shared memory. Axel gave me a link (https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/test/unit/block/shared/src/BlockSharedMemDyn.cpp), but I don't understand, how I get a block of shared memory, like I need it for the matrix multiplication on the cuda examples (http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#shared-memory). Could everyone write a short example code, which demonstrate the usage of shared memory?

best regards
Simeon

**Comment by ax3l** [comment]
@BenjaminW3 @psychocoderHPC let us make René's code in the description of https://github.com/ComputationalRadiationPhysics/alpaka/pull/79 a new alpaka example. what do you think?

**Comment by psychocoderHPC** [comment]
example static shared memory:
```
auto& a = alpaka::block::shared::allocVar<std::uint32_t,0>(acc); //instead of manual counter __CONTER__ can used
auto& b = alpaka::block::shared::allocVar<std::uint32_t,1>(acc);
assert( &a != &b ); // OK!!
```

**Comment by SimeonEhrig** [comment]
The namespace of allocVar should be wrong. I used:
`auto& As = alpaka::block::shared::st::allocVar<uint32_t, 0>(acc);`

And for a block of 2D-Array-Memory (16x16 float):
`auto& Bs = alpaka::block::shared::st::allocVar<cupla::Array<cupla::Array<float, 16>, 16>, 1>(acc);`
(cupla::Array : https://github.com/ComputationalRadiationPhysics/cupla/blob/dev/include/cupla/datatypes/Array.hpp)

**Comment by psychocoderHPC** [comment]
You are right maybe my [example](https://github.com/ComputationalRadiationPhysics/alpaka/issues/353#issuecomment-310610859) from the post before is wrong, I forget tthat we changed the namespaces.

**Comment by BenjaminW3** [comment]
I think that the [unit test for block shared static memory](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/test/unit/block/shared/src/BlockSharedMemSt.cpp) should already be a very good example. It shows the usage of `__COUNTER__` and how to allocate arrays.
Maybe the initial misunderstanding was that it was not clear if dynamic or static block shared memory was required and Alex gave you the link to dynamically allocated block shared memory, which you were not looking for.

I think that the unit tests should be exactly such easy to understand examples with very limited scope. The code itself should be self documenting. 
Our current examples are much heavier end-2-end learning experiences where you can see the relations of the components and the whole picture at once.

**Comment by ax3l** [comment]
Cool, thanks! Even if the examples and tests are already there, can we create a little section in the documentation with e.g. a FAQ + links that new users can go through?

Many new users will be afraid to go straight to the implementation & tests to find a simple example of something they already know from, e.g. the CUDA world.

**Comment by SimeonEhrig** [comment]
I think a FAQ is a good idea, too. I didn't have think about to search after an examples for the functions of the framework in the test cases, until you send me a link. For example, a markdown with hint to to the test cases could be a great convenience for beginners, at the example folder.

**Comment by BenjaminW3** [comment]
> For example, a markdown with hint to to the test cases could be a great convenience for beginners, at the example folder.

A mapping of CUDA functionality to alpaka equivalents has already been available. It might not have been easy to find and it was also a bit outdated, but I have updated it in #356. Within this mapping document it is also possible to link to specific lines within the tests to showcase the usage.
Should we link this directly in the toplevel ReadMe? If yes, where?

**Comment by ax3l** [comment]
Thanks! It's already linked in the README and was simply lacking the section. I think #356 fixes that now, good! :)
