### ISSUE TITLE
support for VERIFY and ASSERT

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#367]
Currently alpaka is using asserts to validate special conditions. Asserts will no available if we comping in release mode.
Some of the checks like [this thread extent check for the accelerator OpenMP2Blocks](https://github.com/ComputationalRadiationPhysics/alpaka/blob/655eb708ff0157b492d73d50727de151b60f6ee6/include/alpaka/exec/ExecCpuOmp2Blocks.hpp#L162) are very important and will not influence the performance.

If we need a verify only for the host side we can use [BOOST_ASSERT,BOOST_VERIFY](http://www.boost.org/doc/libs/1_55_0/libs/utility/assert.html)

**Comment by BenjaminW3** [comment]
Currently `assert` is used to detect programming errors in performance critical paths exactly because it is not available in release builds.
We are already using BOOST_VERIFY within the code-base.
You are right, that the extents should also be checked in release builds. I will change this.

**Comment by BenjaminW3** [comment]
Assertions have been cleaned up. If some of the remaining `assert`s should be available in release mode, please open up a new ticket.
