### ISSUE TITLE
calling two times FIND_PACKAGE("alapka")

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#370]
If  FIND_PACKAGE("alapka") is called two times within a cmake file (e.g. from a project and from the dependent project) than the alpaka cmake config adds all compiler flags two times.
In the case of nvcc usage the compiler crashs because some compiler flags can only be set once.

**Comment by BenjaminW3** [comment]
Which flags do you mean? `alpaka_LIBRARY`, `alpaka_INCLUDE_DIR`, `alpaka_DEFINITIONS`, etc. ?
Or does the target duplicate flags? E.g. when using the preferred way of depending on alpaka via `TARGET_LINK_LIBRARIES(your_library PUBLIC alpaka)` which automatically adds all include dirs, compile flags, definitions, etc.

**Comment by psychocoderHPC** [comment]
I mean `CUDA_NVCC_FLAGS` eg.g https://github.com/ComputationalRadiationPhysics/alpaka/blob/655eb708ff0157b492d73d50727de151b60f6ee6/alpakaConfig.cmake#L337
