### ISSUE TITLE
race condition in `ConcurrentExecPool`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#387]
I am searching a race condition in our program PIConGPU and I am not sure if it is a bug in PIConGPU, cupla or alpaka.

@BenjaminW3 Could it be that https://github.com/ComputationalRadiationPhysics/alpaka/blob/439c98b1a326e0fff73b2beeb77e084207a89647/include/alpaka/core/ConcurrentExecPool.hpp#L608 is the start of a race condition triggered by owner ship issues between threads.

The case:
- 1. a task X is created in thread A: https://github.com/ComputationalRadiationPhysics/alpaka/blob/439c98b1a326e0fff73b2beeb77e084207a89647/include/alpaka/core/ConcurrentExecPool.hpp#L608
-  2. X is given to the task queue https://github.com/ComputationalRadiationPhysics/alpaka/blob/439c98b1a326e0fff73b2beeb77e084207a89647/include/alpaka/core/ConcurrentExecPool.hpp#L614
- 3. adding the task X to the queue is guarded with a lock
https://github.com/ComputationalRadiationPhysics/alpaka/blob/439c98b1a326e0fff73b2beeb77e084207a89647/include/alpaka/core/ConcurrentExecPool.hpp#L79-L81
- 4. after A goes out of the push function a thread B (alpaka stream) can catch the shared pointer with the task X from the queue to execute the task (this will increase the shared_ptr reference counter)
- 5. if A leaves the method `enqueueTask` the shared pointer with the memory of the task X is destroyed (the reference count within the shared pointer is decremented and the object destroyed if ref counter is zero) https://github.com/ComputationalRadiationPhysics/alpaka/blob/439c98b1a326e0fff73b2beeb77e084207a89647/include/alpaka/core/ConcurrentExecPool.hpp#L619
- 6. if thread A destroy the shared_ptr in the same moment where thread B take the task from the queue there can be a race condition during reading and writing of the reference counter of the shared_ptr between both threads.

[cppreference.com](http://en.cppreference.com/w/cpp/memory/shared_ptr)
```
All member functions (including copy constructor and copy assignment) can
be called by multiple threads on different instances of shared_ptr without additional 
synchronization even if these instances are copies and share ownership of the same object. 
If multiple threads of execution access the same shared_ptr without synchronization and 
any of those accesses uses a non-const member function of shared_ptr then
a data race will occur; the shared_ptr overloads of atomic functions can be used 
to prevent the data race.
```

**Comment by psychocoderHPC** [comment]
@BenjaminW3: I am not sure if this is really an issue because we are working on multiple instances of shared_ptr but it would be good if could review the code with an eye on race conditions.

The symptom in PIConGPU is that I create many (few hundred)  events and kernel tasks. PIConGPU is polling all events if they are finished but all events return not finish but alpaka is not executing anything.
It could be something in alpaka is wrong e.g. 
  - a race condition moves all threads to sleep but the queue is filled with tasks
  - the tasks memory is deleted and alpaka works on invalid memory (hard to reproduce with valgrind)
  
But it could also be an issue in PIConGPU or cupla. Due to the fact that I can't see something in PIConGPU and cupla I started to search in alpaka.

**Comment by BenjaminW3** [comment]
I have added numbers to the individual steps.

**Comment by BenjaminW3** [comment]
In step 2, the `upTaskPackage` is moved into the `push` method. This means, that the `enqueueTask` method executed by thead A does not have a reference to the task anymore. The shared_count is **always** 1. Either the enqueuing thread or the queue own the task.

**Comment by psychocoderHPC** [comment]
Ahh ok it was not clear for me that moving a shared_ptr set the old one to nullptr https://stackoverflow.com/a/29644158

**Comment by BenjaminW3** [comment]
In step 4, as well the shared_count will never get greater one. Either the queue or the executing thread own the task, **never** both, see:
https://github.com/ComputationalRadiationPhysics/alpaka/blob/439c98b1a326e0fff73b2beeb77e084207a89647/include/alpaka/core/ConcurrentExecPool.hpp#L90-L101
Within the pop method, the shared_count is raised to 2 by `front` and then decreased to 1 by `pop` before the lock is released and the task is returned.

**Comment by BenjaminW3** [comment]
In the original code `upTaskPackage` once had been a `unique_ptr` (therefore it`s name). This would be much more intuitive but as far as I remeber it is now a `shared_ptr` because the std::queue does not support move-only types.

**Comment by psychocoderHPC** [comment]
Thx for the clarification, I think this code part is save, I think found the issue in the event wait part. I will open a new issue.
