### ISSUE TITLE
CPU event re queuing bug

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#388]
If a event is re queued during a other async stream has a waiting operation to this event in the queue which is not executed than a deadlock of the alpaka system can be created.

- 1. kernel K1 is enqueued to async stream S1
- 2. kernel K2 is enqueued to asnyc stream S2
- 3. event E1 is enqueued to async stream S1
- 4. wait is executed that S2 is waiting on E1 
  - https://github.com/ComputationalRadiationPhysics/alpaka/blob/439c98b1a326e0fff73b2beeb77e084207a89647/include/alpaka/event/EventCpu.hpp#L514-L522
  - m_bIsWaitedFor is set to true to signalize the event that someone is waiting
  - a lambda is enqueued in S2 which starts a wait if E1 is not finished
- 5. K1 finish
- 6. now E1 finish, m_bIsWaitedFor is reseted, all waiting threads are notified but queued wait task from S2 is currently not registered because K2 is still running
- 7. E1 is re queued again but this time in S2
- 8. K2 finish
- 9. the waiting lambda from 4. is executed and because E1 is not finished this code https://github.com/ComputationalRadiationPhysics/alpaka/blob/439c98b1a326e0fff73b2beeb77e084207a89647/include/alpaka/event/EventCpu.hpp#L480-L483 is executed and S2 is waiting on E1, m_bIsWaitedFor is enabled in E1 again

E1 is queued behind the waiting lamda from 4. therefore S2 will never finish (**deadlock**).

I hope I pointed always to the correct specializations of wait. Currently I have no idea how we can solve this issue. 
I was not able to reproduce this issue in a minimal example.

maybe @BenjaminW3 has an idea how we can solve this bug.

**Comment by BenjaminW3** [comment]
This really sounds like a bug.
Waits on events that are not valid anymore (have already been finished) should simply be skipped, so step 9 should never be executed. This could be prevented by adding a counter to the event that is increased each time the event is enqueued (`enqueueCount`). When a stream should wait for an event `enqueueCount` is saved and when the wait is reached it is compared to the current `enqueueCount` count. If they do not match, the event has already been finished and re-enqueued.
I will try to build some tests for the events and simulate this case as well.  This could take some days, but will be solved.

**Comment by psychocoderHPC** [comment]
Thanks that is a good idea I also thought about a counter but  my workflow was to complicated, your idea is much easier. Will test it tomorrow.

**Comment by psychocoderHPC** [comment]
@BenjaminW3 Maybe it is possible to use sleep operations within the kernel to create a test case to reproduce this behavior. This would limit the test to cpu only but this is exact what we need to test.

**Comment by psychocoderHPC** [comment]
closed with #389
