### ISSUE TITLE
proposed renamings (after next release)

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#395]
CUDA uses the name `stream` to describe a sequential FIFO queue of work on the device. Other API's, e.g. OpenCL use the more comon term `CommandQueue` instead.
So my proposal is to rename all of our `stream`s to `queue`s for easier understanding. (`StreamCpuAsync`->`QueueCpuAsync`)
This would be a breaking change and would require changes to all current users. This would at least require a new version. This should best be combined with other major changes (e.g. dropping support of older CUDA versions, etc.). So I would delay this until such a major change is required.

What do you think?

**Comment by ax3l** [comment]
Sure why not, that's a more general naming of it. 

Did you check how it's called in related domains, e.g. the Vulkan API has a similar concept for async executive pipelines.

**Comment by BenjaminW3** [comment]
Vulkan also uses `Queue`.

**Comment by ax3l** [comment]
+1

**Comment by psychocoderHPC** [comment]
I am fine with such a change. But I would propose to  wait a little bit with this braking change.
The reason for this is that we are currently switched with PIConGPU to alpaka, this means alpaka is now used more frequently and we will find more parts we should maybe refactor.

We should collect up coming breaking changes within an issue.

**Comment by ax3l** [comment]
Yes, please tag versions/releases before introducing breaking API changes.

**Comment by BenjaminW3** [comment]
After seeing the ISAAC pull request I propose a second renaming: alpaka uses the name `Size` for types where `Idx` would be more appropriate. so the `size` namespace should be merged into the `idx` namespace and the only trait that the `size` namespace contains should be renamed as well.
Any objections?
