### ISSUE TITLE
`TARGET_COMPILE_OPTIONS` not passed to `nvcc`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#417]
CMake target compile options will not be passed to nvcc.

Test with:
CUDA 8.0 and cmake/3.7.2

```
LIST(APPEND _DEFINITIONS_PRIVATE "-DBOOST_TEST_DYN_LINK")
TARGET_COMPILE_OPTIONS(
    targetName
    PRIVATE ${_DEFINITIONS_PRIVATE})
```

For this explicit example where we need to pass a define to `nvcc` using `ADD_DEFINITIONS("-DBOOST_TEST_DYN_LINK)` is an workaround. But this will set the define for all targets.

CC-ing: @BenjaminW3

**Comment by BenjaminW3** [comment]
Could you try
```
LIST(APPEND _DEFINITIONS_PRIVATE "BOOST_TEST_DYN_LINK")
TARGET_COMPILE_DEFINITIONS(
    targetName
    PRIVATE ${_DEFINITIONS_PRIVATE})
```
instead?
