### ISSUE TITLE
test can not compiled without CI

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#425]
It is not possible to compile the alpaka tests on a system with CUDA.
Test cases like `test/unit/atomic` uses pure C++ host methods within a kernel (e.g.'`std::min`, `std::max`).
This will end in errors like
```
[ 85%] Building NVCC (Device) object CMakeFiles/atomic.dir/src/atomic_generated_AtomicTest.cpp.o
alpaka/test/unit/atomic/src//AtomicTest.cpp(107) (col. 21): error: calling a __host__ function("std::min<unsigned int> ") from a __device__ function("AtomicTestKernel::operator ()< ::alpaka::acc::AccGpuCudaRt< ::std::integral_constant<unsigned long, (unsigned long)1ul> , unsigned long> , unsigned int> ") is not allowed


```

suggestion: refactor the test CMake file to disable unsupported accelerators.

**Comment by BenjaminW3** [comment]
I had already fixed this in a branch which I can not find right now. I had simply replaced the min/max calls by the equivalent ternary operation. I will create a Pull Request.
In which configuration do you trigger this error? In the CI builds this does not happen even in the CUDA builds.

**Comment by psychocoderHPC** [comment]
I used CUDA8 and compiled CUDA only.
