### ISSUE TITLE
example `bufferCopy` used wrong stream

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#427]
The example `bufferCopy` is using a device stream to enqueue a host kernel.
The stream is created [here](https://github.com/ComputationalRadiationPhysics/alpaka/blob/cbd5db26e30d6db2188d976272d3b0e87bed1164/example/bufferCopy/src/bufferCopy.cpp#L179) and the host initialization is enqueued [here](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/example/bufferCopy/src/bufferCopy.cpp#L254).

The line with the enqueue is the trigger for #428.

**Comment by BenjaminW3** [comment]
Fixed with #443
