### ISSUE TITLE
CUDA 8 and gcc 4.9.2 not compatible

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#428]
With gcc 4.9 and CUDA 8 the compiler crash if -DCMAKE_BUILD_TYPE=Debug is set (like in the CI tests).

Tested exmaple `bufferCopy`

**Comment by psychocoderHPC** [comment]
The problem is the compiler flag -G for the cuda compiler, this will disable all optimizations. Maybe -G also increase the compile time of all tests.

**Comment by psychocoderHPC** [comment]
I found the trigger for this issue in #427, but fixing the wrong used stream not solve this issue.

**Comment by psychocoderHPC** [comment]
@BenjaminW3 I thinking about disabling the support for gcc 4.9.2 in combination with CUDA 8+.
A point against 4.9.2 is that full and correct C++11 is only supported since gcc 5.x.

**Comment by BenjaminW3** [comment]
I am always for minimizing the supported compiler version. By removing support for gcc 4.9.2 we would also lose support for CUDA 7.0 and 7.5. How widespread is CUDA 8 on the relevant HPC and dev systems to   support such a change? Currently we have two work arounds in the code base specific to gcc 4.9.

**Comment by psychocoderHPC** [comment]
But we can also only disable gcc 4.x if CUDA 8+ is used.

CC-ing: @ax3l

**Comment by psychocoderHPC** [comment]
@BenjaminW3 Do you know why the buffer test passed the CI tests with CUDA8 and gcc 4.9? Do we check this combination?

**Comment by BenjaminW3** [comment]
But then we are still limited to the C++11 that gcc 4.9.2 supports.

**Comment by psychocoderHPC** [comment]
We can do a release within the next week and than remove the bad compiler^^

**Comment by BenjaminW3** [comment]
CUDA 8 & gcc 4.9 should be checked in [job#4](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/.travis.yml#L92) but this is a Debug build and not a release build.

**Comment by psychocoderHPC** [comment]
is this testing all the examples?

**Comment by BenjaminW3** [comment]
The examples are build in all cases except when `ALPAKA_ACC_GPU_CUDA_ONLY_MODE` is set, which is not the case.
My current PR build: https://travis-ci.org/ComputationalRadiationPhysics/alpaka/jobs/290435436
Using gcc 4.9.4 and CUDA 8.0.
Maybe we should update the gcc version in the readme table to state 4.9.4 instead of 4.9.2.

**Comment by ax3l** [comment]
It's not a good idea to drop `gcc 4.9` just because `-G` is not working with it. It's still wide-spread used and explicitly compatible with CUDA 8.

We can throw warnings or errors if the combination is used.

**Comment by BenjaminW3** [comment]
Yes, as a first step we could drop the '-G' flag when building for CUDA 8+ and issue a warning.

**Comment by psychocoderHPC** [comment]
#416 is not passing because of this issue, I will do a test and remove `-G` in #416 to check if the CI than pass all tests.

**Comment by ax3l** [comment]
We can also add the `-G` issue as a note to the install/compatebility list. `-G` is quite tricky due to it's high register consumption in many cases and warning that we do not support it well with GCC 4.9(.2) is fine imho.

**Comment by ax3l** [comment]
Idea:
Additional to adding it to the docs as a note: Since we set `-G` in CMake on the debug build type, we can just throw a warning for GCC 4.9 and *not* set `-G` automatically. (Of course, control via CXXFLAGS is stil possible but users need to know what they do if they want it with that combo.)

**Comment by ax3l** [comment]
@BenjaminW3 should we also add a note about the `-G` issue to the install instructions or will the current patch be sufficient?

**Comment by BenjaminW3** [comment]
I think the CMake warning is enough.

**Comment by ax3l** [comment]
All right!

**Comment by psychocoderHPC** [comment]
I need to correct myself, in #416 I get the some issue with all CUDA <= 8.0 and with CLANG 3.7.1.
I will remove the usage of `-G` for CUDA <= 8.0 for GCC <5.0 and CLANG 3.7.X

**Comment by psychocoderHPC** [comment]
fixed in #435
