### ISSUE TITLE
travid CI test case take to long

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#436]
One of your tests takes to long and will not pass finish. https://travis-ci.org/ComputationalRadiationPhysics/alpaka/jobs/291978888.
I tried also to restart the test but without success.

@BenjaminW3 Can we shrink the tested examples?

**Comment by BenjaminW3** [comment]
This is the same as #414. I am already investigating. For now it should be enough to simply restart the  individual job.
