### ISSUE TITLE
memBuf testcase always failing for CUDA

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/alpaka#441]
I noticed, that the test case `test/unit/mem/buf/build` always fails for the CUDA back end when it comes to allocate memory of size 0 [here](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/test/unit/mem/buf/src/BufTest.cpp#L133). This [check](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/test/common/include/alpaka/test/mem/view/ViewTest.hpp#L132) fails as `cudaMalloc` returns a NULL pointer if the extent is 0. This works fine on CPU back ends as malloc _may_ return an unique non-null pointer even if the extent is 0.

However even this is not guaranteed, as the man pages states:
> If size is 0, then malloc() returns either NULL, or a unique pointer value that can later be successfully passed to free().

So the question is: What is the desired behaviour?
And should the test case be changed so that it does not fail?

**Comment by BenjaminW3** [comment]
You are right. I think we should not check for `!= nullptr` there unconditionally. The pointer is only required to be non-null when `extent.prod() > 0`

**Comment by BenjaminW3** [comment]
Could you please try if #442 is correct?
Are there any more test runtime failures? The CI can not execute those those when CUDA is enabled and I do not have the required hardware right now...

**Comment by theZiz** [comment]
I will check this monday. :wink:

**Comment by BenjaminW3** [comment]
Has the 'monday' you mentioned already come? ;-)

**Comment by theZiz** [comment]
I did not find time yet, but I will check it now :)

**Comment by theZiz** [comment]
Looks good to me except for a small typo (_"When the extent is 0, the pointer is undefined but it should still be possible **to** get it."_).

I also compiled and ran your code, it works fine. :)

**Comment by BenjaminW3** [comment]
fixed with #442
