### ISSUE TITLE
compilation problem in the integration test matMul

### ISSUE THREAD

**Issue by ivandrodri** [ComputationalRadiationPhysics/alpaka#446]
I have this compilation problem with the matMul example:

####################################################################

[ 80%] Building NVCC (Device) object matMul/CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o
/home/ivan/Desktop/Alpaka_git/alpaka/test/integ/matMul/src//main.cpp(297) (col. 15): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/il_to_str.c", line 7191

1 catastrophic error detected in the compilation of "/tmp/tmpxft_00003f69_00000000-5_main.cpp4.ii".
Compilation aborted.
Aborted (core dumped)
CMake Error at matMul_generated_main.cpp.o.cmake:282 (message):
  Error generating file
  /home/ivan/Desktop/Alpaka_git/alpaka/test/integ/build/matMul/CMakeFiles/matMul.dir/src/./matMul_generated_main.cpp.o

matMul/CMakeFiles/matMul.dir/build.make:63: recipe for target 'matMul/CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o' failed
make[2]: *** [matMul/CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o] Error 1
CMakeFiles/Makefile2:332: recipe for target 'matMul/CMakeFiles/matMul.dir/all' failed
make[1]: *** [matMul/CMakeFiles/matMul.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

#####################################################################

thanks in advance for any help!

**Comment by psychocoderHPC** [comment]
Could you please post which OS do you have used and which compiler, boost and CUDA (if used).
And all commands used up to the broken compile.

Am 16. November 2017 09:37:37 MEZ, schrieb ivandrodri <notifications@github.com>:
>I have this compilation problem with the matMul example:
>
>####################################################################
>
>[ 80%] Building NVCC (Device) object
>matMul/CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o
>/home/ivan/Desktop/Alpaka_git/alpaka/test/integ/matMul/src//main.cpp(297)
>(col. 15): internal error: assertion failed at:
>"/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/il_to_str.c",
>line 7191
>
>
>1 catastrophic error detected in the compilation of
>"/tmp/tmpxft_00003f69_00000000-5_main.cpp4.ii".
>Compilation aborted.
>Aborted (core dumped)
>CMake Error at matMul_generated_main.cpp.o.cmake:282 (message):
>  Error generating file
>/home/ivan/Desktop/Alpaka_git/alpaka/test/integ/build/matMul/CMakeFiles/matMul.dir/src/./matMul_generated_main.cpp.o
>
>
>matMul/CMakeFiles/matMul.dir/build.make:63: recipe for target
>'matMul/CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o' failed
>make[2]: ***
>[matMul/CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o] Error 1
>CMakeFiles/Makefile2:332: recipe for target
>'matMul/CMakeFiles/matMul.dir/all' failed
>make[1]: *** [matMul/CMakeFiles/matMul.dir/all] Error 2
>Makefile:83: recipe for target 'all' failed
>make: *** [all] Error 2
>
>#####################################################################
>
>thanks in advance for any help!
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ComputationalRadiationPhysics/alpaka/issues/446

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ivandrodri** [comment]
I am using ubuntu 16.04, boost 1.65 and CUDA 8.0 .   I went to matMul  and create a build folder to generate the project with "cmake .." . Cmake works but when I run make this is the full output:


ivan@ivan-XPS-15-9560:~/Desktop/Alpaka/alpaka/test/integ/matMul/build$ make
[ 33%] Built target alpaka
[ 66%] Built target common
[ 83%] Building NVCC (Device) object CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o
/home/ivan/Desktop/Alpaka_git/alpaka/test/integ/matMul/src//main.cpp(299): error: argument list for class template "alpaka::mem::view::ViewPlainPtr" is missing
          detected during:
            instantiation of "auto alpaka::meta::detail::ForEachTypeHelper<TList<T, Ts...>>::forEachTypeHelper(TFnObj &&, TArgs &&...)->void [with TList=std::tuple, T=alpaka::test::acc::detail::AccCpuSerialIfAvailableElseVoid<alpaka::dim::DimInt<2UL>, uint32_t>, Ts=<alpaka::test::acc::detail::AccCpuThreadsIfAvailableElseVoid<alpaka::dim::DimInt<2UL>, uint32_t>, alpaka::test::acc::detail::AccCpuOmp2BlocksIfAvailableElseVoid<alpaka::dim::DimInt<2UL>, uint32_t>, alpaka::test::acc::detail::AccCpuOmp2ThreadsIfAvailableElseVoid<alpaka::dim::DimInt<2UL>, uint32_t>, alpaka::test::acc::detail::AccGpuCudaRtIfAvailableElseVoid<alpaka::dim::DimInt<2UL>, uint32_t>>, TFnObj=MatMulTester &, TArgs=<uint32_t &, uint32_t &, uint32_t &>]" 
/home/ivan/Desktop/Alpaka_git/alpaka/include/alpaka/meta/ForEachType.hpp(122): here
            instantiation of "auto alpaka::meta::forEachType<TList,TFnObj,TArgs...>(TFnObj &&, TArgs &&...)->void [with TList=alpaka::test::acc::EnabledAccs<alpaka::dim::DimInt<2UL>, uint32_t>, TFnObj=MatMulTester &, TArgs=<uint32_t &, uint32_t &, uint32_t &>]" 
(434): here

1 error detected in the compilation of "/tmp/tmpxft_00004d24_00000000-7_main.cpp1.ii".
CMake Error at matMul_generated_main.cpp.o.cmake:282 (message):
  Error generating file
  /home/ivan/Desktop/Alpaka_git/alpaka/test/integ/matMul/build/CMakeFiles/matMul.dir/src/./matMul_generated_main.cpp.o


CMakeFiles/matMul.dir/build.make:910: recipe for target 'CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o' failed
make[2]: *** [CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/matMul.dir/all' failed
make[1]: *** [CMakeFiles/matMul.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by psychocoderHPC** [comment]
Do you use the master or dev branch?

Am 16. November 2017 10:39:59 MEZ, schrieb ivandrodri <notifications@github.com>:
>I am using ubuntu 16.04, boost 1.65 and CUDA 8.0 .   I went to matMul 
>and create a build folder to generate the project with "cmake .." .
>Cmake works but when I run make this is the full output:
>
>
>ivan@ivan-XPS-15-9560:~/Desktop/Alpaka/alpaka/test/integ/matMul/build$
>make
>[ 33%] Built target alpaka
>[ 66%] Built target common
>[ 83%] Building NVCC (Device) object
>CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o
>/home/ivan/Desktop/Alpaka_git/alpaka/test/integ/matMul/src//main.cpp(299):
>error: argument list for class template
>"alpaka::mem::view::ViewPlainPtr" is missing
>          detected during:
>instantiation of "auto alpaka::meta::detail::ForEachTypeHelper<TList<T,
>Ts...>>::forEachTypeHelper(TFnObj &&, TArgs &&...)->void [with
>TList=std::tuple,
>T=alpaka::test::acc::detail::AccCpuSerialIfAvailableElseVoid<alpaka::dim::DimInt<2UL>,
>uint32_t>,
>Ts=<alpaka::test::acc::detail::AccCpuThreadsIfAvailableElseVoid<alpaka::dim::DimInt<2UL>,
>uint32_t>,
>alpaka::test::acc::detail::AccCpuOmp2BlocksIfAvailableElseVoid<alpaka::dim::DimInt<2UL>,
>uint32_t>,
>alpaka::test::acc::detail::AccCpuOmp2ThreadsIfAvailableElseVoid<alpaka::dim::DimInt<2UL>,
>uint32_t>,
>alpaka::test::acc::detail::AccGpuCudaRtIfAvailableElseVoid<alpaka::dim::DimInt<2UL>,
>uint32_t>>, TFnObj=MatMulTester &, TArgs=<uint32_t &, uint32_t &,
>uint32_t &>]" 
>/home/ivan/Desktop/Alpaka_git/alpaka/include/alpaka/meta/ForEachType.hpp(122):
>here
>instantiation of "auto
>alpaka::meta::forEachType<TList,TFnObj,TArgs...>(TFnObj &&, TArgs
>&&...)->void [with
>TList=alpaka::test::acc::EnabledAccs<alpaka::dim::DimInt<2UL>,
>uint32_t>, TFnObj=MatMulTester &, TArgs=<uint32_t &, uint32_t &,
>uint32_t &>]" 
>(434): here
>
>1 error detected in the compilation of
>"/tmp/tmpxft_00004d24_00000000-7_main.cpp1.ii".
>CMake Error at matMul_generated_main.cpp.o.cmake:282 (message):
>  Error generating file
>/home/ivan/Desktop/Alpaka_git/alpaka/test/integ/matMul/build/CMakeFiles/matMul.dir/src/./matMul_generated_main.cpp.o
>
>
>CMakeFiles/matMul.dir/build.make:910: recipe for target
>'CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o' failed
>make[2]: *** [CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o]
>Error 1
>CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/matMul.dir/all'
>failed
>make[1]: *** [CMakeFiles/matMul.dir/all] Error 2
>Makefile:83: recipe for target 'all' failed
>make: *** [all] Error 2
> 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ComputationalRadiationPhysics/alpaka/issues/446#issuecomment-344868228

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ivandrodri** [comment]
yes, I am on develop branch

**Comment by BenjaminW3** [comment]
I have seen similar errors before with some gcc versions. Which host compiler do you use?

**Comment by ivandrodri** [comment]
I am using gcc 5.4.0

**Comment by BenjaminW3** [comment]
Currently we do not have this combination of compilers/tools in the CI.
I have tried to simulate your environment in CI and created #447. I have used Ubuntu 16.04, CUDA 8, gcc 5.4 and boost-1.65.1. I was not able to trigger your error. However, I have found a different one, CUDA 8.0 supports the `--expt-relaxed-constexpr` flag only with gcc 4.9 and not with gcc 5.4. After fixing this, everything except the constexpr test compiles and runs successfully.

**Comment by ivandrodri** [comment]
I still have the same problem in the matMult code. What combination  of compilers/tools in the CI do you recommend?

**Comment by BenjaminW3** [comment]
The matMul test is excluded from CI because it does not compile when using nvcc as compiler.
I have found the commit that disabled it beaa37ba84a1d7b2d163db87b794076fa7d7cf4b. However, there we can not find any reason. I remember seeing the exact same compiler frontend error you are seeing. I am sorry, but I doubt that this test will ever be fixed for this compiler combination.
I will try to enable it for as many compiler combinations as possible and document the reasons why it is excluded for others.
Please note, even without this test there are other errors for this compiler combination that will be fixed/worked around with  #447.

**Comment by BenjaminW3** [comment]
@ivandrodri My preferred compiler would always be the newest version supported by alpaka. So currently CUDA 9.0 with gcc 5. (gcc 6 is not yet supported).
I have reviewed the test and found a workaround for the compiler crash. It is fixed now on develop. Please tell us if there are any more issues!
