### ISSUE TITLE
CUDA 9 requires Boost >=1.65

### ISSUE THREAD

**Issue by bertwesarg** [ComputationalRadiationPhysics/alpaka#456]
Boost <1.65 does not work with CUDA 9, because in CUDA 9 the macro `__CUDACC_VER__` is now a string constant, and these old boost versions still use this macro, instead of the new `__CUDACC_VER_[MAJOR,MINOR,BUILD]__` macros. Can we somehow detect this combination in CMake and fail gracefully, instead of:

```
In file included from /home/wesarg/opt/cuda-9.0.176/include/common_functions.h:50:0,
                 from /home/wesarg/opt/cuda-9.0.176/include/cuda_runtime.h:115,
                 from <command-line>:0:
/home/wesarg/opt/cuda-9.0.176/include/crt/common_functions.h:65:24: error: token ""__CUDACC_VER__"" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__"
                        ^
/home/wesarg/opt/boost-1.63.0-gcc6/include/boost/config/compiler/nvcc.hpp:22:34: note: in expansion of macro ‘__CUDACC_VER__’
 #if !defined(__CUDACC_VER__) || (__CUDACC_VER__ < 70500)  
                                  ^~~~~~~~~~~~~~
/home/wesarg/opt/cuda-9.0.176/include/crt/common_functions.h:65:24: error: token ""__CUDACC_VER__"" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__"
                        ^
/home/wesarg/opt/boost-1.63.0-gcc6/include/boost/config/compiler/nvcc.hpp:26:6: note: in expansion of macro ‘__CUDACC_VER__’
 #if (__CUDACC_VER__ > 80000) && (__CUDACC_VER__ < 80100)  
      ^~~~~~~~~~~~~~
```

**Comment by BenjaminW3** [comment]
This could be added somewhere within the CUDA configuration in the [alpakaConfig.cmake](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/alpakaConfig.cmake#L338). Taking into account `Boost_MAJOR_VERSION, Boost_MINOR_VERSION, Boost_SUBMINOR_VERSION` should be possible there. Please note: we do not support 1.65.0 with CUDA 9. We only support 1.65.1.

**Comment by ax3l** [comment]
1.65.1 and newer to be precise.

Yes, just check for CUDA first and then increase the boost requirement or throw a CMake error if the found version is too old. This dependency should also be documented in the README please.
