### ISSUE TITLE
OSX: ranlib: file libalpaka.a(Dymmy.cpp.o) has no symbols

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/alpaka#460]
Compiling PIConGPU with alpaka on OSX fails in the CMake step.

The main reason might be the "dummy" library that is created which we should replace with a more modern, CMake 3 `INTERFACE` target instead.

```
ranlib: file libalpaka.a(Dummy.cpp.o) has no symbols
```

Environment:
- macOS "High Sierra" (10.13.3)
- Apple Clang 9.0
- CMake 3.10.2
- Boost 1.65.1
- OpenMP 2.0 "blocks" backend

**Comment by ax3l** [comment]
besides the needed fix, can we maybe add a single osx entry to our travis-ci build matrix?

**Comment by ax3l** [comment]
@psychocoderHPC the same issue likely also appears in cupla

**Comment by psychocoderHPC** [comment]
I can look into it but not before the next week.
I think a first workaround before a cmake update (which takes a little bit time) would be to add a dummy function into the dummy library.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by BenjaminW3** [comment]
Is there any way to ignore this linker error?
As far as I know, the `INTERFACE` library type produces problems for IDE projects generated by CMake. With some of the last updates it was made possible to attach source files to such a library, but those will appear as part of the consuming library and not the interface library itself. I have no problem with a dummy function returning the version ;-)

We could add osx to our travis-ci builds. However this is a large undertaking and I do not have a Mac to develop/test this. Furthermore, OSX builds seem to be a bottleneck on travis at the moment.

**Comment by ax3l** [comment]
> As far as I know, the INTERFACE library type produces problems for IDE projects generated by CMake. 

Can you link that issue?
Technically, we just need to create a (not-building but solely installing) target in CMake:

```cmake
add_library(alpaka INTERFACE)
target_include_directories(alpaka INTERFACE
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:include>)

target_link_libraries(alpaka INTERFACE boost::boost) # ...
# ...

install(TARGETS alpaka
# ...
)
```

For OSX on travis I just mean *a single* test, not the full matrix again. Just to make sure the general logic works, e.g. with the latest boost.

**Comment by BenjaminW3** [comment]
I do not want to have the whole test matrix on mac as well. But even a single compiler/boost/nvcc compilation seems to be much work, at least to me.

Your pseudo-code from above should work. However, you will not see the alpaka sources anymore when generating an IDE project (e.g. Visual Studio).

There is a bug ticket for this avaiable as well as a workaround: https://gitlab.kitware.com/cmake/cmake/issues/15234

**Comment by ax3l** [comment]
Ok, the work-around is a one-line with a custom target for the IDE that is never called. We should do that.

**Comment by BenjaminW3** [comment]
I will try out the work-around in the next days.
