### ISSUE TITLE
Contribute the Boost.Predef extensions to boost mainline

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#464]
* [x] BOOST_LANG_CUDA
 https://github.com/boostorg/predef/pull/71
* [x] BOOST_COMP_NVCC
 https://github.com/boostorg/predef/pull/72
* [x] BOOST_ARCH_CUDA_DEVICE -> BOOST_ARCH_PTX
 https://github.com/boostorg/predef/pull/73

**Comment by BenjaminW3** [comment]
Please review and comment on the PRs if you see any issues.
I am not yet sure, if BOOST_ARCH_PTX is the best name. But given x86, MIPS etc. it might be the best match.

**Comment by BenjaminW3** [comment]
I do not think that BOOST_COMP_CLANG_CUDA should be contributed because it is no real compiler but identical to the combination of BOOST_LANG_CUDA && BOOST_COMP_CLANG

**Comment by ax3l** [comment]
> BOOST_ARCH_PTX

ok with me.

> BOOST_COMP_CLANG_CUDA

Hm, can you elaborate what each of the macros would stand for? Probably it's not bad to still have it to specifically nail down the *device* compiler side. (e.g. you could have clang on the host and nvcc on the device as well)

**Comment by ax3l** [comment]
Side note: it might be worth noting that my CUDA developers request to add boost to the internal Nvidia QA (nvcc) test suite is currently seeing action (08/2017, no. 1971626). Will inform you if anything comes out of this.

**Comment by BenjaminW3** [comment]
Everything is now merged and will hopefully appear in the next boost release!
