### ISSUE TITLE
enable usage of lambdas as kernels

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#47]
CUDA 7.5 allows to pass lambdas into the global kernel with the flag `--expt-extended-lambda`. See [here](http://on-demand.gputechconf.com/gtc/2015/webinar/gtc-express-everything-you-need-to-know-cuda-7-5-webinar.pdf).

``` C++
__device__ int result;
template <typename T>
__global__ void kernel(T in) { result = in(4); }

void foo(void) {
    int x = 30;
    kernel<<<1,1>>>(
        [=] __device__ (int in) {
            return in * x; // x captured by value
        })
}
```

We have to make sure that ALPAKA_FN_ACC can be used in the place of `__device__` especially in non-cuda code.

**Comment by BenjaminW3** [comment]
CUDA 8.0 supports Heterogeneous C++ Lambda. We could add a test now.

**Comment by erikzenker** [comment]
Nice ! I was looking forward to this.

**Comment by bussmann** [comment]
Awesome!

**Comment by erikzenker** [comment]
Let me prepare an example and test for it.
