### ISSUE TITLE
Boost 1.67.0 beta1

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/alpaka#470]
Boost 1.67.0 beta1 is tagged.

Todo: check if the next boost release still works with CUDA and alpaka (before it becomes a release).

**Comment by BenjaminW3** [comment]
Do you want to try it out locally?
My boost.predef changes will most probably not get integrated into this boost release.

**Comment by BenjaminW3** [comment]
I created a branch using this boost build and it worked successfully. So there should not be any problem.

**Comment by ax3l** [comment]
Hurray, thanks for trying. Just to make sure: you also tested with nvcc?

**Comment by BenjaminW3** [comment]
I think so ;-)

**Comment by ax3l** [comment]
Ok cool, that's the main dependency causing trouble between releases (with nvcc).
