### ISSUE TITLE
DevMan 

### ISSUE THREAD

**Issue by jiradaherbst** [ComputationalRadiationPhysics/alpaka#482]
I tried to write my first Alpaka program to implement Gauss Elimination and it was finally successful! At least the program gave the correct results for several test cases. Along the way, I encountered the following  3 issues:
1. DevMan (I discussed this point with Alex already) 
             alpaka::dev::DevMan<Host> seems to be replaced by alpaka::pltf
   for retrieving device purpose. Or if DevMan is still there, I could not find it in the documentation.

I will put the other two issues seperately.

**Comment by BenjaminW3** [comment]
Yes, the DeviceManager has been renamed to Platform see https://github.com/ComputationalRadiationPhysics/alpaka/pull/167

**Comment by ax3l** [comment]
@jiradaherbst great to hear you implemented your first Alpaka program! :sparkles: 

The documentation of Platform is indeed outdated and will be updated in #485
