### ISSUE TITLE
Bugfix release 0.3.1

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#491]

**Comment by ax3l** [comment]
Added project in https://github.com/ComputationalRadiationPhysics/alpaka/projects/1

**Comment by BenjaminW3** [comment]
Is there anything left to do?
Does it work in PIConGPU?
Else I would close this ticket and release this version.

**Comment by ax3l** [comment]
@psychocoderHPC forgot to update here, but he finalized the release on Friday already. The `release-0.3.1` branch contains all fixes and the last commit is tagged as release. We could still update the `master` branch though #520

**Comment by BenjaminW3** [comment]
Ok. Then I will finalize this release!
