### ISSUE TITLE
Rename BOOST_ARCH_CUDA_DEVICE to BOOST_ARCH_PTX

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#524]
... to match the naming merged into boost

**Comment by ax3l** [comment]
Likely in boost 1.58+, right?

**Comment by BenjaminW3** [comment]
Yes, I hope so. But I still want to rename it in alpaka as well just now.

**Comment by tdd11235813** [comment]
FYI, for HIP backend I would move to `BOOST_ARCH_HSA` ([HSA](https://gpuopen.com/rocm-do-you-speaka-my-language/)), which seems more appropriate anyway, instead of `BOOST_ARCH_HIP_DEVICE` now.

**Comment by theZiz** [comment]
This does not make sense to me as HIP != HSA. So I would propose `BOOST_ARCH_HIP` instead as the back end can always be CUDA and in that case `BOOST_ARCH_HSA` does not make much sense.

**Comment by BenjaminW3** [comment]
I do not see how `BOOST_ARCH_HIP` should make any sense. The `BOOST_ARCH` macros are used to detect the real hardware architecture a piece of code is currently compiled for (even if we misuse it in some places). `HIP` is no architecture because it can be `BOOST_ARCH_PTX` or `BOOST_ARCH_X86` or something different.
Is `HSA` a real architecture?

**Comment by theZiz** [comment]
So do we need `BOOST_ARCH_HSA` at all except for back end (speaking of hip back ends) specific specializations?

**Comment by BenjaminW3** [comment]
I do not currently see any usage for such a define. It is not used anywhere in the current HIP PR. All usages are commented out.

**Comment by tdd11235813** [comment]
ok, give me another try, for HIP I would suggest to distinguish in the HIP compilation phase, whether nvcc or hcc is used and then set `BOOST_ARCH_PTX` or `BOOST_ARCH_HSA` (or _HSAIL)?

**Comment by theZiz** [comment]
Makes sense for me.

**Comment by BenjaminW3** [comment]
Original issue solved with #527

**Comment by ax3l** [comment]
I would like if we also try not to hijack issues.
Open fresh issues for fresh questions and refer via linking to old issues, please :-)

Keeps everything focused.
