### ISSUE TITLE
Setting ALPAKA_ACC_GPU_CUDA_ONLY_MODE does not disable other backends

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/alpaka#550]
The issue was originally mentioned in [this discussion](https://github.com/ComputationalRadiationPhysics/alpaka/pull/547)

It seems setting this flag does not actually disable other backends, contradicting what the name suggests.

**Comment by BenjaminW3** [comment]
As written in the original issue: We could fix this by disabling all accelerator backends except CUDA if the `ALPAKA_ACC_GPU_CUDA_ONLY_MODE` flag is given.
However, this could also result in conflicts. We may want to think about the general way we enable accelerators. We have multiple cases here:
1) User does not request any accelerators when calling CMake: All available accelerators are enabled and warnings are printed for those which are not available✔️ 
2) User explictly requests accelerators: All available accelerators are enabled and the ones explicitly requested are disabled with a warning when they are not available ❗️ I would prefer to let configure fail in this case.
3) User explicitly requests `ALPAKA_ACC_GPU_CUDA_ONLY_MODE` and disables all other accelerators explicitly ❕ It should not be necessary to explicitly disable all other accelerators when this flag is given.
4) User explicitly requests `ALPAKA_ACC_GPU_CUDA_ONLY_MODE` and leaves the defaults: Error ❗️ This should work
5) User explicitly requests `ALPAKA_ACC_GPU_CUDA_ONLY_MODE` and explictly requests CPU accelerators: Error ✔️

**Comment by sbastrakov** [comment]
I think case 2 should be generalized. A user requests some accelerators and disables some. If there is an intersection between these two sets, Error. Otherwise, enable all available accelerators that are not explicitly disabled, report a warning or error if smth requested is not available.
