### ISSUE TITLE
Rng: STL MT has huge state

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/alpaka#575]
The currently implemented `std::mt19937` state of the [`alpaka::rand::RandStl`](https://github.com/ComputationalRadiationPhysics/alpaka/blob/0d5657a474334d821b43616bd0e92b08643ddc8d/include/alpaka/rand/RandStl.hpp#L51-L70) is of 2KByte size.

That's way too large for most applications, as seen by @psychocoderHPC here:
https://github.com/ComputationalRadiationPhysics/picongpu/issues/2653

Maybe we also want to implement some sort of TinyMT, e.g.
http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/TINYMT/
https://github.com/MersenneTwister-Lab/TinyMT ([32-bit header](https://github.com/MersenneTwister-Lab/TinyMT/blob/master/tinymt/tinymt32.h), [usage example](https://stackoverflow.com/a/46186567/2719194))

Refs:
http://www.cplusplus.com/reference/random/mt19937/
https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine

**Comment by ax3l** [comment]
Fun-fact, there is also *Mersenne Twister for Graphic Processors* (https://github.com/MersenneTwister-Lab/MTGP), might be the one in the CUDA SDK...

**Comment by psychocoderHPC** [comment]
Also the std library give us a lot of other possibilities https://en.cppreference.com/w/cpp/numeric/random

**Comment by ax3l** [comment]
The other stdlib rngs, only the lcg with small state, have horrible properties :)

**Comment by sbastrakov** [comment]
@ax3l not all LCGs are evil, however should be used with caution ofc. In a way, Mersenne Twister is not that different - it's also linear and operates essentially by modulo (but in a different field).

**Comment by ax3l** [comment]
@psychocoderHPC found your other engine, the device engine that feeds of the entropy pool ;-)
https://en.cppreference.com/w/cpp/numeric/random/random_device

**Comment by sbastrakov** [comment]
Probably not much, as the comment in the example given by your link suggests.

On a serious note, in case @ax3l is allergic to LCGs, maybe it is worth to implement a xorwow on CPU, at least as a temporary solution (and so it is the same generator as in curand)? Should be rather simple.

**Comment by ax3l** [comment]
> not all LCGs are evil, however should be used with caution

yes but that's playing with details, the stdlib implements the usual suspect: https://en.cppreference.com/w/cpp/numeric/random/linear_congruential_engine

> xorwow on CPU

yes, but also the little TinyMT header linked above is very simple.

**Comment by ax3l** [comment]
@BenjaminW3 am I missing it or is the only way to create an RNG currently via the `createDefault` trait? Can we select the generator somewhere?

**Comment by BenjaminW3** [comment]
@ax3l Yes, you are right, there is only `createDefault` at the moment , see the still open ticket #390. @psychocoderHPC proposed a solution for this in there.
