### ISSUE TITLE
Rng: CPU Namings

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/alpaka#577]
The CPU rng should not be called `RandStl` but `RandStdlib`.

STL is the standard template library, which is part of the stdlib. `<random>` is of course not part of the STL.

**Comment by sbastrakov** [comment]
Agree.

**Comment by BenjaminW3** [comment]
👍 

I am still unsure how #579 plays into this. It adds something outside of the StdLib. It may need its own new file.
Maybe it would be better to seperate between the devices supported: `cuda/RandCuRand`, `cpu/RandStdLib`, `cpu/RandTinyMt`?
