### ISSUE TITLE
Multiprocessor/SMP count function

### ISSUE THREAD

**Issue by kloppstock** [ComputationalRadiationPhysics/alpaka#599]
It would be nice to have a function which returns the number of Multiprocessors/SMPs for a given accelerator. This could be used to ensure that only multiples of these are used as a block size.

**Comment by sbastrakov** [comment]
I'm not sure, but I think @kloppstock meant not this, but the number of NUMA-nodes, e.g. for a system with multiple CPUs on shared memory. And not CPU accelerators seem to just set `m_multiProcessorCount ` to 1.

**Comment by BenjaminW3** [comment]
I will close this issue for now. If it is not the correct answer, we can simply reopen it.
