### ISSUE TITLE
Standalone/Auxiliary Headers

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/alpaka#601]
I think during the "install" of Alpaka, we should provide auxiliary headers such as "alpaka/backend/omp2b.hpp" that pre-define all CMake-set defines for users.

With such, user using interpreters such as `cling` or tools such as #600 can just do:
```C++
#include <alpaka/backend/omp2b.hpp>
#include <alpaka/alpaka.hpp>

#include <iostream>

// ...
```

and start learning/playing/debugging alpaka right away.

(Note: assuming the user starts e.g. a `cling -std=c++11 -x cuda` or `cling -std=c++11-x -fopenmp` powered kernel.)

The "auxiliary" headers could be very simplified regarding alpaka features. E.g., one could limit to single backends.

Maybe we also could/need to work some compiler-workaround activations into such headers, instead of cmake-setting them.

Do I miss something important here? I think that would be awesome!

**Comment by ax3l** [comment]
cc @SimeonEhrig

**Comment by sbastrakov** [comment]
I think it's a great idea! Also maybe helpful even for some "normal" (clone repo and build locally) alpaka users. I would probably use sometimes it to change quicker in my MSVS instead of re-doing cmake / changing preprocessor macro in project settings.

**Comment by ax3l** [comment]
I think for general projects, CMake targets and even install is definitely the way to go.
Nevertheless, I want people to learn and experiment with Alpaka quickly with modern tools (binder, compiler explorer, etc.) and REPL, for which a simple include would be ideal (also linking is no issue there, no need to stay header-only).

**Comment by SimeonEhrig** [comment]
I talked to Benjamin about the feature. We have the idea that we offer two solutions. One is Axel’s solution. Providing headers with defines for each backend. It should work without "cmake install".

The second solution is to create a custom header with cmake during the install time. The header should contain the defines of all backends which were available during install time. Additionally, the custom header should be automatically include by the `alpaka.hpp` header, so we only need to include the `alpaka.hpp` and all available backends are enabled.

Maybe the second feature should be disabled by default and activated via cmake flag.

**Comment by BenjaminW3** [comment]
I will close this issue for now. The basic standalone headers have been implemented and we should create new tickets for extending this if necessary.
