### ISSUE TITLE
Do not throw an error when P2P access is not possible.

### ISSUE THREAD

**Issue by tdd11235813** [ComputationalRadiationPhysics/alpaka#615]
On systems, where GPUs are not directly connected via PCIe, P2P test fails. However, a warning message should be ok. I did not think about it when checking #602 .

Current Copy.hpp<cuda> code:
```C++
ALPAKA_CUDA_RT_CHECK(cudaDeviceCanAccessPeer(&canAccessPeer, devSrc, devDst));                                                
if(!canAccessPeer) {                                                                                                          
    std::string const sError("Peer access is not possible! src=" + std::to_string(devSrc) + " dst=" + std::to_string(devDst));
    throw std::runtime_error(sError);                                                                                         
}                                                                                                                             
```

**Comment by BenjaminW3** [comment]
Yes, the test should not throw an exception but should simply print a message.
However, in real code, there should be an exception beause the explicit request to do a peer copy can not be handled.
I think the correct thing to do would be to check `cudaDeviceCanAccessPeer` before excuting the rest of the test.
