### ISSUE TITLE
Replace BOOST_VERIFY in tests, as it does nothing in release mode

### ISSUE THREAD

**Issue by tdd11235813** [ComputationalRadiationPhysics/alpaka#617]
`BOOST_VERIFY` behaves [like an assert](https://www.boost.org/doc/libs/1_65_1/libs/assert/doc/html/assert.html#boost_verify). And it does nothing, when `NDEBUG` is defined, which means in release mode tests like `verifyBytesSet` and `verifyViewsEqual` do not test (it only evaluates the expression itself). 
It can be reproduced, when the `==` is switched to `!=` in the verify kernels. In release mode, the test mistakenly passes.

And just as an additional minor issue: `BOOST_VERIFY` does not report the positive state back to the test suite (as it is just an BOOST_ASSERT in non-release mode).
For example, if there would be only `BOOST_VERIFY` calls in the `memView` test, it would need something like a `BOOST_CHECK(true);` in the end, otherwise Boost does not know about the state of the test (it just passed without flagging it true or false). Of course, within the `memView` test there is a `BOOST_REQUIRE_EQUAL` (==`BOOST_TEST_REQUIRE`), which does report back. So here, `memView` has a defined state. For the memP2P test, this is missing, thus this test can have an undefined state, which yields a log message:
```
Test case memP2P/memP2PTest<alpaka__acc__AccGpuCudaRt<std__integral_constant<unsigned_long,_1ul>,_long>> did not check any assertions
```

Relates to #367 and #616 .

**Comment by BenjaminW3** [comment]
It would be best if the `VerifyBytesSetKernel` and `VerifyViewsEqualKernel` would not use `BOOST_VERIFY`, but would do a simple if and print an error else. Furthermore, the kernels should write the boolean success state and the calling methods should read this value and check it via `BOOST_CHECK`.

**Comment by tdd11235813** [comment]
ok, yes that sounds good. There are other places which use `BOOST_VERIFY` as well, but some of them are maybe supposed to behave assert-like.

**Comment by BenjaminW3** [comment]
I am currently working on removing `BOOST_VERIFY` from the whole repo and replacing it by printf error reporting and correct returns from the kernels.
