### ISSUE TITLE
Memory pinning of BufCpu throws static assert when CUDA is not enabled!

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/alpaka#620]
I am using pinned memory right now and it works very well with CUDA, but the same code throws a static assert as pinning is not implemented for non cuda code:

https://github.com/ComputationalRadiationPhysics/alpaka/blob/151e0c0b231deb0bbadf2c5ede273c55114b51de/include/alpaka/mem/buf/BufCpu.hpp#L487

So I have to copy the ugly, surrounding `#ifdef` inside of my project code. I would prefer that pinning of memory that does not support pinning is just ignored or to implement it for non-cuda (if this makes sense at all)

**Comment by BenjaminW3** [comment]
I would prefer to have this implemented in a portable way that does not rely on CUDA. However, I did not yet have a look at it and there may not be a portable solution.
Simply ignoring it does not seem to be a good idea to me. The user explicitly called the pinning method and expects it to be pinned afterwards.

**Comment by theZiz** [comment]
Well, tbh I don't care whether my memory is pinned. I just wanted async copy with cuda to work. So maybe leaving the function as it is and adding a function, which "prepares" memory for async operations in some way (in that case: pinning) may be an idea? It was really hard to figure out why the async copy was not working and to find that pinning is even directly supported in alpaka.

**Comment by BenjaminW3** [comment]
I think an `alpaka::mem::buf::prepareForAsyncCopy` using a `alpaka::mem::buf::detail::PrepareForAsyncCopy` should work. I know that this is relatively specific to CUDA but you do not need to call it and it would not harm if you do it on CPU because it would do nothing there. So go ahead if you need it ;-)

**Comment by theZiz** [comment]
Sounds much like what I want. I will give implement it and open an pull request. :wink:

**Comment by psychocoderHPC** [comment]
Note: a portable way to pin memory is to use `hwloc`'s `hwloc_set_membind()`

**Comment by fwyzard** [comment]
> Note: a portable way to pin memory is to use `hwloc`'s `hwloc_set_membind()`

Do you know if `hwloc_set_membind()` can be used in place of `cudaHostRegister()` to pin memory in a way that accelerates GPU copies, or if it can only be used when CUDA/HIP are not being used ?

The [documentation](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1ge8d5c17670f16ac4fc8fcb4181cb490c) of `cudaHostRegister()` says
> Page-locks the memory range specified by `ptr` and `size` and maps it for the device(s) as specified by flags.
> This memory range also is added to the same tracking mechanism as `cudaHostAlloc()` to automatically accelerate calls to functions such as `cudaMemcpy()`. 

I would guess that `hwloc_set_membind()` can do the pinning, but not the CUDA-specific registration done by  `cudaHostAlloc()`/`cudaHostRegister()` ?
