### ISSUE TITLE
QueueCpuAsync tells it is empty although a task is still running

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/alpaka#621]
I am having the following problem: I am writing a simple blur kernel example, in which the image is chunked in smaller parts, which shall be copied, processed and copied back in parallel in different queues to overlap copying and computing. The idea is, if one of these queue is empty, I know I can savely feed a new chunk to this queue.

However the check for emptyness of the stream does not work because of theese lines in https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/core/ConcurrentExecPool.hpp#L595 :
```C++
if(popTask(currentTaskPackage))
{
    currentTaskPackage->runTask();
}
```
There a task is popped from the queue and processed. However if I check for the emptyness of the queue **after** `popTask(currentTaskPackage)`, it will return `true` although `currentTaskPackage->runTask();` may still run. So in my example I am starting to copy data to the "free" chunk although the copying back of data is not finished (yet).

Maybe the same problems occurs for `alpaka::wait::wait( … )`, I did not check this.

**Comment by BenjaminW3** [comment]
I knew that this would come up one day.
The current CPU behaviour is by-design and the expected behaviour. However, we might need to fix this.
`alpaka::wait::wait(queue)` works correctly, as this is what the unit test does as well.
Even easier should be to enqueue a simple CPU callback. `alpaka::queue::enqueue(queue, []() noexcept {eneuque_next_task();})`

**Comment by theZiz** [comment]
Well, at least waiting is no option for me, because I want to poll and not to wait ;)

**Comment by theZiz** [comment]
Btw, in that case the current CPU behavior is wrong and against the documentation by design. You may expect this behaviour, but nobody else will: https://computationalradiationphysics.github.io/alpaka/namespacealpaka_1_1stream.html#af98dd42189df6240d6996d7e38f0061a It states for `alpaka::queue::empty( … )`:
> Tests if the queue is empty (all ops in the given queue have been completed).

:wink:

**Comment by BenjaminW3** [comment]
You are right and it should be fixed
There are multiple conflicting expectations here.
The async CPU Queue reuses the work queue from the thread and fiber backends. There `empty` really means that the queue of unprocessed tasks is empty but there can still be some threads that are executing tasks that they have already popped.
What `alpaka::queue::empty` should be returning and what is correctly documented is not that the queue is empty but that it is empty and all threads have finished processing. So it should not be called `empty` in the first place but `alpaka::queue::idle(queue)`.
I will have a look at fixing this.

**Comment by BenjaminW3** [comment]
Please review the fix PR and even better: please test it in your code.
