### ISSUE TITLE
Selecting available accelerators does not check versions of OpenMP

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/alpaka#628]
As I understand, in case no specific accelerators are requested via cmake arguments, alpaka tries to use all accelerators available. However, with OpenMP it only checks that OpenMP is found and then both OMP2 and OMP4 accelerators are enabled (or rather not disabled). In case of building for Visual Studio only OpenMP 2 is supported though and so OMP4 accelerators are not suitable. I think it is better to add checks for versions of OpenMP and only enable the supported accelerators. In case that it reasonable, I can provide a PR for that (should be just a couple of lines).

**Comment by ax3l** [comment]
> I think it is better to add checks for versions of OpenMP and only enable the supported accelerators.

Sounds legit, feel free to provide a PR and we take a look in-code!

**Comment by sbastrakov** [comment]
@ax3l okay, will do today.

**Comment by BenjaminW3** [comment]
👍
