### ISSUE TITLE
Unified host/device attributes of constructor/destructor (nvcc vs. hcc)

### ISSUE THREAD

**Issue by tdd11235813** [ComputationalRadiationPhysics/alpaka#629]
While trying the HC compiler on the HIP back-end (PR #505), it complained about all the non-unified host/device attributed constructors/destructors, because behavior of destructor can be undefined then. So the destructor has to unify the host/device attributes of the constructors. This is also part of the [C++AMP programming model](http://download.microsoft.com/download/2/2/9/22972859-15c2-4d96-97ae-93344241d56c/cppampopenspecificationv12.pdf) (section 2.2.2), and HCC seems to follow and to check this.

C++AMP, 2.2.2:

> Constructors can have overloads that are differentiated by restriction specifiers.

> Since destructors cannot be overloaded, **the destructor must contain a restriction specifier that covers the union of restrictions on all the constructors**. (A destructor can achieve the same effect of overloading by calling auxiliary cleanup functions that have different restriction specifiers.)

An error will be thrown, if host/device attributes for constructor and destructor mismatch:
```
alpaka/idx/gb/IdxGbRef.hpp:61:29: error: Destructor's restriction specifiers must cover the union of restrictions on all constructors
                /*virtual*/ ~IdxGbRef() = default;
```
Current code:
https://github.com/ComputationalRadiationPhysics/alpaka/blob/36bbc56584f47eecbc5a570534d4a85ade172c08/include/alpaka/idx/gb/IdxGbRef.hpp#L48-L61

Now, when we add these attributes to please HCC:

```C++
/*virtual*/ ALPAKA_FN_HOST ~IdxGbRef() = default;
```

then NVCC feels bad. It is just a warning though (an explanation can be found [here](https://stackoverflow.com/questions/46469062/warning-host-annotation-on-a-defaulted-function-is-ignored-why))

```
/alpaka/include/alpaka/idx/gb/IdxGbRef.hpp(61): warning: __host__ annotation is ignored on a function("~IdxGbRef") that is explicitly defaulted on its first declaration
```

An idea could be to invent another macro (© @theZiz ;)):
```C++
/*virtual*/ ALPAKA_FN_ATTR_HCC(ALPAKA_FN_HOST) ~IdxGbRef() = default;
```
In the HCC back-end it places the macro, otherwise it is empty.

What do you think?

Edit: another error could be, when invoking a host function within a host-device function:
```
error: call from AMP-restricted function to CPU-restricted function
```

**Comment by tdd11235813** [comment]
... the second option would be to add the compiler flag for cuda:
```
-Xcudafe="--diag_suppress=2886"
```
which still requires the destructor refactoring, but does not need a special macro for that.
This suppresses the warnings from nvcc (confirmed).

**Comment by BenjaminW3** [comment]
As far as I understood, HCC tries to mimic CUDA and should allow for easy porting. If they take this really serious, they would also mimic the nvcc behaviour of not requiring attributes on defaulted/deleted functions. However, this will not change right now (if at all) so we have to live with it.

Could you play around with this code a bit? Could we simply delete the destructor? What happens when we make it virtual?

The `ALPAKA_FN_ATTR_HCC` macro should work but is ugly and what is much worse: it has to be used by an end-user as well when he writes code with such destructors.

**Comment by tdd11235813** [comment]
If the destructor is deleted, then the compiler seems to generate the matching ones and the error is gone.
I only see default destructors in the error log, so commenting out would be an option here.
But this error will also appear on concretized destructors. So the end-user would run into this again.

I also found a [minimal working example](https://gist.github.com/tdd11235813/5f378d35c2de66aa56715377f405fb0b) for the host device error mentioned in #505. 
Issue is: host calls a host-device function which calls another host function. We suppressed this in nvcc, as it is just a warning there. I'll ask on the HIP side, if there is a simple solution in HIP(HCC)  for both issues.

**Comment by tdd11235813** [comment]
ok about the constructor/destructor thing. 

Possible workaround (have not run full test yet):
- Every destructor is flagged with a `__host__ __device__` macro
  - HCC is happy
  - NVCC 8.0 is happy
  - NVCC 9.x emit warnings, however, this antidot helps for all NVCC 9.x versions:
```cmake
LIST(APPEND CUDA_NVCC_FLAGS "-Xcudafe --diag_suppress=esa_on_defaulted_function_ignored")
```
- NVCC would always be happy with non-defaulted destructors (does not help us)
- clang(CUDA) still has to be tested

Let's see how the two issues on the HIP side will be responded.

**Comment by tdd11235813** [comment]
tested bit more around with HIP(HCC) and ctors/dtors signatures. It works, when all the host-devices flags are removed from all ctors/dtors. It seems, nvcc mostly can deal with it.
Since, HIP will only allowed to run in HIP-only mode in alpaka, only the interfacing classes are relevant (e.g. CUDA related classes are irrelevant).
Needs more investigation later on. HIP(HCC) is lowered in priority at the moment.

**Comment by ax3l** [comment]
> HCC tries to mimic CUDA and should allow for easy porting. If they take this really serious

But if as the initial PR description quotes, the open standard C++ AMP does a proper definition for future implementations, than it's actually more a NVCC issue than an issue of HCC, potentially MSVC's implementation, etc. and we should try to move in that direction.

**Comment by psychocoderHPC** [comment]
Note: Kokkos is also using this (`LIST(APPEND CUDA_NVCC_FLAGS "-Xcudafe --diag_suppress=esa_on_defaulted_function_ignored")`) workaround: https://github.com/kokkos/kokkos/issues/1473#issuecomment-373440552

I tested it together with PIConGPU and is work!

**Comment by tdd11235813** [comment]
ok, with #668 we have a solution, but maybe there are still methods, which do not fit yet in the HCC world of host-device-signature constraints. I agree with @axel, that the HCC way would be generally preferable, as it is more strict than nvcc regarding their specifications.
HIP also provided an explanation and a [member detection example](https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_bugs.md) ('detector' refers to the test method in the `Has_call_operator`).
But you also cannot call a host function within a host-device function, see aforementioned [example](https://gist.github.com/tdd11235813/5f378d35c2de66aa56715377f405fb0b). That host function must be either host-device or maybe even non-annotated to pass through.
Not sure, if we keep this issue open therefore.

**Comment by BenjaminW3** [comment]
I would like to close this issue. The PR has been merged and everything seems to work for now so there is nothing to do.
If there are new issues, we can still open a new ticket or reopen this one.
