### ISSUE TITLE
Provide default constructors for BufCpu and the like

### ISSUE THREAD

**Issue by krzikalla** [ComputationalRadiationPhysics/alpaka#638]
We have a class, which provides a view to alpaka-allocated or user-allocated (runtime decision) memory.
If user-allocated memory is used, then the member holding the alpaka-allocated memory can't be initialized.

Current workaround:
```

class A 
{
  using HostBufferType = decltype(alpaka::mem::buf::alloc<T, size_t>(...));
  std::unique_ptr<HostBufferType> hostBuffer_;  // default constructible
}

```

I want to get rid of the std::unique_ptr. Solution is easy, just introduce a `BufCpu() = default;`
Same for `BufCudaRt` and maybe other similar classes.

**Comment by krzikalla** [comment]
I don't see how a default-constructible BufCpu requires a default-constructible DevCpu. BufCpu holds only a smart_ptr, which can be simply zero-initialized. Also, actually I don't need to track the state of my hostBuffer_, since I hold a view to the memory anyway. The view is initialized on ctor time - either with the allocated buffer or the user memory. Afterwards the hostBuffer_ isn't touched anymore - only implicitly during destruction time.

That said, I understand your design philosophy. I guess, optional is the best way to express the design (I prefer std::optional over boost::optional, but that's another topic).

**Comment by psychocoderHPC** [comment]
@BenjaminW3 I will reopen this issue. You points are all valid but please give all developer the time to think about it. Maybe there is a solution maybe not.

**Comment by psychocoderHPC** [comment]
Note: `std::optional` and `std::variant` are both c++17 feature and my be not usable (depending on the requirements). To switch to `boost` is maybe also not a solution if @krzikalla do not like to introduce boost into the project beside that alpaka is using it.

**Comment by ax3l** [comment]
`std::variant` has a great C++11 implementation that we are using in [other projects](https://github.com/openPMD/openPMD-api): https://github.com/mpark/variant

**Comment by ax3l** [comment]
@krzikalla would a `makeBuf` factory solve your needs as well? I can understand both arguments above.

**Comment by krzikalla** [comment]
@ax3l Are you aware, that your link points to an April's fool?

And no, I don't see how a factory could solve the issue. Either you allow default constructed (and thus somehow invalid) buffer types or you don't. Both variants have their pros and cons.

**Comment by ax3l** [comment]
Ha, that's very disappointing ;)
