### ISSUE TITLE
`--expt-relaxed-constexpr` considered harmful

### ISSUE THREAD

**Issue by bertwesarg** [ComputationalRadiationPhysics/alpaka#640]
I'm getting in conflict with the `--expt-relaxed-constexpr` flag to NVCC. I have the following reproducer (GCC 7.3.0 and CUDA 9.2.88):

```c++
class Foo
{
public:
    Foo() : _v(0) {}
    Foo(int v) : _v(v) {}
    inline static Foo & Null()
    {
        return Foo::_null;
    }
    constexpr int operator()() const noexcept { return _v; }
private:
    int _v;
    static Foo _null;
};
Foo Foo::_null;

class Bar
{
public:
    Bar() : _foo(nullptr) {}
    Bar(Foo* foo) : _foo(foo) {}
    constexpr Foo & foo() const noexcept
    {
        return (_foo != nullptr) ? *_foo : Foo::Null();
    }
private:
    Foo* _foo;
};

int
main()
{
    Bar bar;
    const Foo& foo = bar.foo();
    return foo();
}
```
The error is than:

```
test.cpp(24): error: identifier "Foo::_null" is undefined in device code
```

removing the `--expt-relaxed-constexpr` flag works.

**Comment by ax3l** [comment]
Side note: beginning with an `_` is also considered harmful ;-)
https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

**Comment by ax3l** [comment]
Do you have a https://developer.nvidia.com/ account? The bug tracker there usually is quite responsive.

**Comment by bertwesarg** [comment]
> Side note: beginning with an `_` is also considered harmful ;-)
> https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

Luckily the C++ mangling saves me here.

**Comment by ax3l** [comment]
Your example compiles for me: https://cuda.godbolt.org/z/KL6FQo

**Comment by bertwesarg** [comment]
> Do you have a https://developer.nvidia.com/ account? The bug tracker there usually is quite responsive.

No, but I report it here, because Alpaka sets this flag by default, without an option not to set it:
https://github.com/ComputationalRadiationPhysics/alpaka/blob/8e206bdad75da2704bdac7060a61115a97304df2/alpakaConfig.cmake#L492

**Comment by bertwesarg** [comment]
> Your example compiles for me: https://cuda.godbolt.org/z/KL6FQo

How do I see the full flags used?

**Comment by ax3l** [comment]
I updated the link to compiler explorer

**Comment by bertwesarg** [comment]
> > Your example compiles for me: https://cuda.godbolt.org/z/KL6FQo
> 
> How do I see the full flags used?

This is rather expected, as this only does not compile, if the mentioned flag is given.

**Comment by ax3l** [comment]
Can't confirm: https://cuda.godbolt.org/z/UbzivE

**Comment by ax3l** [comment]
> Probably something in the combination wit GCC 7.X - which X btw?

What's your exact GCC version?

**Comment by bertwesarg** [comment]
> What's your exact GCC version?

```
ing built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 
```

**Comment by bertwesarg** [comment]
> Can't confirm: https://cuda.godbolt.org/z/UbzivE

This is the command alpakaconfig.cmake generates:
```
$ nvcc \
    /test.cpp \
    -x=cu \
    -c \
    -o test.o \
    -ccbin /usr/bin/c++ \
    -m64 \
    -DALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED \
    -DALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLED \
    -DALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLED \
    -DALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLED \
    -DALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLED \
    -DALPAKA_ACC_GPU_CUDA_ENABLED \
    -DALPAKA_DEBUG=0 \
    -Xcompiler ,\"-fopenmp\",\"-g\" \
    --expt-extended-lambda \
    --expt-relaxed-constexpr \
    --generate-code arch=compute_30,code=sm_30 \
    --generate-code arch=compute_30,code=compute_30 \
    -std=c++11 \
    --use_fast_math \
    --ftz=false \
    -DNVCC \
    -I/home/wesarg/opt/cuda-9.2.88/include \
    -I/usr/include \
    -I/home/wesarg/Work/Mephisto/alpaka/include
```

**Comment by ax3l** [comment]
Thx! And your exact CUDA 9.2 version? They just published a bugfix release, 9.2.148. (9.2.88 was the initial CUDA 9.2 release).

**Comment by ax3l** [comment]
Playing with your code, I can only trigger such an error when adding randomly `__host__ __device__` qualifiers to the `constexpr` and `inline` member functions of both classes.

**Comment by ax3l** [comment]
Can you also add a description what you try to do with the code? Looks like a host-device singleton which can't really work cross host-device.

As a note, since we are in C++11 you could also try if direct (`const`?) initialization of `Foo:_null` changes your situation: https://en.cppreference.com/w/cpp/language/static

**Comment by bertwesarg** [comment]
> And your exact CUDA 9.2 version?

9.2.88. Will try 9.2.148.

**Comment by bertwesarg** [comment]
The original code is from an external project, where I have limited control over. I actually don't want to use any of that code on the device.

**Comment by ax3l** [comment]
I tried the code again with GCC 7.3 on Ubuntu 18.04 and still can't reproduce your code snippet to fail. But I am using already NVCC 9.2.148 for it:
```bash
$ docker pull nvidia/cuda:9.2-devel-ubuntu18.04
$ docker run -it nvidia/cuda:9.2-devel-ubuntu18.04
```

**Comment by bertwesarg** [comment]
> Will try 9.2.148.

That did not changed anything for me.

**Comment by bertwesarg** [comment]
> Can you also add a description what you try to do with the code?

The code is actually not intended for the device.

**Comment by bertwesarg** [comment]
> and both
> 
> ```
> root@fe95e23d5081:/# nvcc --expt-relaxed-constexpr main.cpp 
> root@fe95e23d5081:/# nvcc --expt-relaxed-constexpr main.cpp -std=c++11
> ```
> 
> work

Try:

```
$ nvcc --expt-relaxed-constexpr main.cpp -x cu
```

So its the `-x cu` flag. But that flag is added by `alpakaConfig.cmake`.

**Comment by bertwesarg** [comment]
> As a note, since we are in C++11 you could also try if direct (`const`?) initialization of `Foo:_null` changes your situation:

Do you mean 'in-class initialization'? That did not worked with GCC:
 
```
test.cpp:13:22: error: in-class initialization of static data member ‘const Foo Foo::_null’ of incomplete type
     const static Foo _null{};
 ```

```c++
class Foo
{
public:
    Foo() : _v(0) {}
    Foo(int v) : _v(v) {}
    inline static const Foo & Null()
    {
        return Foo::_null;
    }
    constexpr int operator()() const noexcept { return _v; }
private:
    int _v;
    const static Foo _null{};
};
const Foo Foo::_null;
```

**Comment by ax3l** [comment]
> So its the -x cu flag. But that flag is added by alpakaConfig.cmake.

Good catch! I forgot to make my main a `main.cu`:
```bash
$ nvcc --expt-relaxed-constexpr main.cu
# main.cu(24): error: identifier "Foo::_null" is undefined in device code
#
# 1 error detected in the compilation of "/tmp/tmpxft_000001b0_00000000-8_main.cpp1.ii".
```

**Comment by ax3l** [comment]
Reported upstream as Nvidia Bug report 2393246

**Comment by ax3l** [comment]
@bertwesarg does Alpaka compile for your application without `--expt-relaxed-constexpr`? if so, we can make this an option.

**Comment by bertwesarg** [comment]
Sure it does.

**Comment by bertwesarg** [comment]
That's the whole point of this issue, that Alpaka adds this option unconditionally!

**Comment by ax3l** [comment]
PR open in #641, let's see if we can also add it to CI so it keeps working for you in the future as well.

**Comment by ax3l** [comment]
@bertwesarg just for curiosity, did you already try if NVCC in CUDA 10 fixed that issue?

**Comment by bertwesarg** [comment]
> @bertwesarg just for curiosity, did you already try if NVCC in CUDA 10 fixed that issue?

Works.

**Comment by ax3l** [comment]
Thx for testing!

**Comment by ax3l** [comment]
Option for disabling each of the two experimental nvcc flags in #641
