### ISSUE TITLE
CUDA Tests broken in Develop

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/alpaka#644]
What are the exact, minimal CMake parameters to run the tests *manually* with CUDA enabled?

I am trying
```bash
mkdir build
cd build

cmake .. -DALPAKA_ACC_GPU_CUDA_ENABLE=ON -DALPAKA_CUDA_ARCH="37"
# ok

make -j
# ok

ctest -V
# fail 9/26
```

on a K80 but many tests fail:
```
65% tests passed, 9 tests failed out of 26

Total Test time (real) = 112.39 sec

The following tests FAILED:
	 12 - atomic (Failed)
	 13 - blockShared (Failed)
	 14 - blockSync (Failed)
	 18 - kernel (Failed)
	 19 - memBuf (Failed)
	 20 - memView (Failed)
	 21 - memP2P (Failed)
	 24 - rand (Failed)
	 25 - time (Failed)
Errors while running CTest
make: *** [test] Error 8
```

e.g. `rand`:
```
$ ./test/unit/rand/rand 
Running 18 test cases...
rand: /home/huebl/src/alpaka/include/alpaka/workdiv/WorkDivHelpers.hpp:192: alpaka::workdiv::WorkDivMembers<TDim, TIdx> alpaka::workdiv::subDivideGridElems(const alpaka::vec::Vec<TDim, TVal>&, alpaka::vec::Vec<TDim, TVal>, const alpaka::acc::AccDevProps<TDim, TIdx>&, bool, alpaka::workdiv::GridBlockExtentSubDivRestrictions) [with TDim = std::integral_constant<long unsigned int, 1ul>; TIdx = short int]: Assertion `isValidAccDevProps(accDevProps)' failed.
unknown location(0): fatal error: in "rand_/defaultRandomGeneratorIsWorking<N6alpaka3acc12AccGpuCudaRtISt17integral_constantImLm1EEsEE>": signal: SIGABRT (application abort requested)
/home/huebl/src/alpaka/test/unit/rand/src//RandTest.cpp(152): last checkpoint: "defaultRandomGeneratorIsWorking" entry.
rand: /home/huebl/src/alpaka/include/alpaka/workdiv/WorkDivHelpers.hpp:192: alpaka::workdiv::WorkDivMembers<TDim, TIdx> alpaka::workdiv::subDivideGridElems(const alpaka::vec::Vec<TDim, TVal>&, alpaka::vec::Vec<TDim, TVal>, const alpaka::acc::AccDevProps<TDim, TIdx>&, bool, alpaka::workdiv::GridBlockExtentSubDivRestrictions) [with TDim = std::integral_constant<long unsigned int, 2ul>; TIdx = short int]: Assertion `isValidAccDevProps(accDevProps)' failed.
unknown location(0): fatal error: in "rand_/defaultRandomGeneratorIsWorking<N6alpaka3acc12AccGpuCudaRtISt17integral_constantImLm2EEsEE>": signal: SIGABRT (application abort requested)
/home/huebl/src/alpaka/test/unit/rand/src//RandTest.cpp(152): last checkpoint: "defaultRandomGeneratorIsWorking" entry.
rand: /home/huebl/src/alpaka/include/alpaka/workdiv/WorkDivHelpers.hpp:192: alpaka::workdiv::WorkDivMembers<TDim, TIdx> alpaka::workdiv::subDivideGridElems(const alpaka::vec::Vec<TDim, TVal>&, alpaka::vec::Vec<TDim, TVal>, const alpaka::acc::AccDevProps<TDim, TIdx>&, bool, alpaka::workdiv::GridBlockExtentSubDivRestrictions) [with TDim = std::integral_constant<long unsigned int, 3ul>; TIdx = short int]: Assertion `isValidAccDevProps(accDevProps)' failed.
unknown location(0): fatal error: in "rand_/defaultRandomGeneratorIsWorking<N6alpaka3acc12AccGpuCudaRtISt17integral_constantImLm3EEsEE>": signal: SIGABRT (application abort requested)
/home/huebl/src/alpaka/test/unit/rand/src//RandTest.cpp(152): last checkpoint: "defaultRandomGeneratorIsWorking" entry.

*** 3 failures are detected in the test module "rand"
```

with CUDA 8.0.44, Boost 1.62 on Hypnos (HZDR) and `develop` as of 8e206bdad75da2704bdac7060a61115a97304df2

**Comment by BenjaminW3** [comment]
Your commands look fine.
The failing assertion could simply be a bug in the assertion or the `isValidAccDevProps` function it uses. Have you tried building and testing a release build?

**Comment by psychocoderHPC** [comment]
I will ahve a look into it. I am currently compiling the tests. This will take a time :coffee:

**Comment by psychocoderHPC** [comment]
error see bellow: This means in a previews call there is an error. 
```
unknown location(0): fatal error: in "axpy/calculateAxpy<N6alpaka3acc12AccGpuCudaRtISt17integral_constantImLm1EEmEE>": std::runtime_error: /bigdata/hplsim/scratch/widera/alpaka/include/alpaka/queue/QueueCudaRtAsync.hpp(351) 'cudaStreamSynchronize_ptsz( queue.m_spQueueImpl->m_CudaQueue)' A previous CUDA call (not this one) set the error  : 'cudaErrorInvalidDeviceFunction': 'invalid device function'!
```

**Comment by BenjaminW3** [comment]
The last change that could have influenced all those tests was the one that introduced return values for all the test kernels to correctly test them in release builds. It heavily changed the `alpaka/test/common/include/alpaka/test/KernelExecutionFixture.hpp` which now creates a one byte buffer before each test that is copied to the host after the execution.

**Comment by psychocoderHPC** [comment]
@ax3l A note: `cmake .. -DALPAKA_ACC_GPU_CUDA_ENABLE=ON -DALPAKA_CUDA_ARCH="37"` will enable CUDA as additional backend for testing but all other backends will also enabled because of the auto detection. Not sure if this is important for you.

**Comment by ax3l** [comment]
@psychocoderHPC yes, I also tried with `-DALPAKA_ACC_GPU_CUDA_ONLY_MODE=ON`, getting the same results.

**Comment by psychocoderHPC** [comment]
I am not sure but it looks like there is something fully broken in the kernel execution part or before. 
I can currently not localize where the issue is coming from.

If I not found the issue today I will have next week a look into it. (Because of private reasons I am maybe the rest of the week not at work)

**Comment by BenjaminW3** [comment]
I was able to reproduce a similar error on windows. I will try to have a look at it as soon as possible.

**Comment by BenjaminW3** [comment]
On a first sight it might be an unsupported type. The `TestIdxs` tuple has been changed in the mentioned change. All the errors I have seen have `TIdx = short int`.

**Comment by psychocoderHPC** [comment]
note: I was going back over a half year in the history and also with older versions I have the issue that the tests are not running.
@BenjaminW3 please leave a message here if you find a solution. I will do the same if I find whats going on.

**Comment by tdd11235813** [comment]
strange thing, I also did runtime tests in that time, but most likely not for CUDA8.
I can confirm the failed tests, except that memP2P is working here (tested with 1x K80), so only 8 tests failed instead of 9.

**Comment by ax3l** [comment]
Left-over after #646 is merged:

```
The following tests FAILED:
	 15 - memBuf (Failed)
	 16 - memView (Failed)
	 17 - memP2P (Failed)
Errors while running CTest
```

See https://github.com/ComputationalRadiationPhysics/alpaka/pull/646#issuecomment-423490474

**Comment by BenjaminW3** [comment]
Reopened as it is not fully solved.
