### ISSUE TITLE
TBB Backend

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/alpaka#65]
From various OpenMP courses, the recommendation to rather use the [TBB library](https://www.threadingbuildingblocks.org/intel-tbb-tutorial) (Intel Threading Building Blocks; compiler independent) over pragmas for native multi-core and phi applications *in C++* should motivate us to implement it as a backend.

Besides it's homepage, the [wikipedia article](https://en.wikipedia.org/wiki/Threading_Building_Blocks) also gives a good overview.

Note: compared to [Cilk(++)](https://en.wikipedia.org/wiki/Cilk) ([web](https://www.cilkplus.org/)) which is rather high-level, TBB is dual licensed OSS (GPLv2 & Freeware commercial) and there are quite a few forks on github that, e.g., are even optimized to support [POWER](https://github.com/intel-tbb).

[FAQ entries](https://www.threadingbuildingblocks.org/faq/26) regarding Xeon Phi.

**Comment by erikzenker** [comment]
While diving deeply into Alpaka I wrote an [TBB back-end draft](https://github.com/erikzenker/alpaka/tree/topic-tbb). It is similar to the OpenMP 2.0 block parallel and can be used as foundation for a more enhanced version.

**Comment by BenjaminW3** [comment]
At first sight this looks very good and easy!

**Comment by bussmann** [comment]
Love it! Can't wait to see this IRL.

**Comment by ax3l** [comment]
@erikzenker great work, cool!

could you maybe name it `[ALPAKA_ACC_]CPU_B_TBB_T_SEQ[_ENABLE]` so the strategy is visibly the same as in OpenMP2 block parallel?

**Comment by erikzenker** [comment]
Well, then I will change the macro name an prepare an pull request. The ci should run through in the current state.
