### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/alpaka#656]
Discuss!

![logo](https://user-images.githubusercontent.com/385145/46021229-78ff3a80-c0e0-11e8-9041-ce495a3cf78c.png)

**Comment by tdd11235813** [comment]
:) The idea is great! BUT, a thing which distracted me is the brown color and that the lines of the alpaka in the alpaka are a lil bit too sketchy. Maybe the smoothness & style factor can be increased to look more streamlined, while keeping the sweet look. Then I will really like it :)

**Comment by theZiz** [comment]
The colours are HZDR / picongpu / isaac related. I changed the brownish orange to a more orange hzdr orange.
It is quite hard to give the impression of a alpaca head, while making this it looked more like a hyena most of the time. I tried to smooth the neck a bit. I will try some other ideas tomorrow.
![logo](https://user-images.githubusercontent.com/385145/46024729-b1eedd80-c0e7-11e8-920f-6e90119ba198.png)

**Comment by tdd11235813** [comment]
I see alpaka is not easy :) I am curious how a blue inner contour line will look like, so the head silhouette is complete and the orange bigger contour is the light coming from the back(-ends).

**Comment by ax3l** [comment]
Colors and logo are cool. Can you make the front of the face less wobbly?

I have the impression the orange is too wide for the fine lines of blue... Maybe you can decrease the orange width or increase the blue-lines' width a little?

**Comment by BenjaminW3** [comment]
Will this be a SVG?

**Comment by theZiz** [comment]
> Colors and logo are cool. Can you make the front of the face less wobbly?

Unfortunately no. Every try I gave to make the face less wobbly ended in a hyena or some my little pony character. :roll_eyes: I can of course give you the SVG to play around yourself :wink: 

> I have the impression the orange line is too thick for the fine lines of blue... Maybe you can decrease the orange width or increase the blue-lines' width a little? Alternatively, maybe alternate the width of the orange line around the details, neck and/or ears?

Hm, funny, I thought the orange line may be a bit too thin. I will try more variants after this post, maybe this solves this impression a bit. :smiley: 

> (Is the font free?)

The font is Latin Modern Sans Quotation. Of course I tried to to use a free font. The license is GUST Font License, which is legally the same as the [LaTeX Project Public License](https://en.wikipedia.org/wiki/LaTeX_Project_Public_License).

> Will this be a SVG?

It is already, but I can't upload SVGs in issues.

> In the png the ear is filled with white while the rest is transparent.

You are right, this is not intended (for this design proposal). Can be fixed if we decide for that design. :wink:

I will upload some more variants I discussed with @tdd11235813 yesterday in the next hour.

**Comment by theZiz** [comment]
Okay, here more suggestions, I gave them version numbers, so we can talk about them better. :wink: 
Version 3:
![v3](https://user-images.githubusercontent.com/385145/46065919-b1038d80-c173-11e8-81c6-169eabf340f6.png)
Version 4:
![v4](https://user-images.githubusercontent.com/385145/46065920-b1038d80-c173-11e8-8723-3290828402e9.png)
Version 5:
![v5](https://user-images.githubusercontent.com/385145/46065921-b1038d80-c173-11e8-85d2-baf473b71486.png)
Version 6:
![v6](https://user-images.githubusercontent.com/385145/46065922-b1038d80-c173-11e8-8347-a8f84b60274a.png)
Version 7:
![v7](https://user-images.githubusercontent.com/385145/46065923-b19c2400-c173-11e8-8950-3a8de4d2eb5e.png)
Version 8:
![v8](https://user-images.githubusercontent.com/385145/46065924-b19c2400-c173-11e8-86b9-3d8a9190bdbf.png)

**Comment by psychocoderHPC** [comment]
I like version 1 but I do not like the font.

**Comment by theZiz** [comment]
I see your points and will give it another shot. However for this I would change the font. I chose this font because of two reasons:
* it had quite thin letters
* it is free

So, point me to a better font which fulfills these requirements and I will give it another try. If you want to play yourself, I put all versions in a zip file attached here: [alpaka.zip](https://github.com/ComputationalRadiationPhysics/alpaka/files/2418813/alpaka.zip)
You need inkscape and probably the font Latin Modern Sans Quotation.

**Comment by theZiz** [comment]
Maybe this font („Dosis“) fits better? I furthermore tried to fit the p-head better in the font lines.

![v3_1](https://user-images.githubusercontent.com/385145/46069905-e791d600-c17c-11e8-8a18-1e9bde90c811.png)

**Comment by theZiz** [comment]
As suggested by @psychocoderHPC in an offline discussion, version 3 without the front-neck-line but with face:
![v3_2](https://user-images.githubusercontent.com/385145/46071084-8c151780-c17f-11e8-8dd3-62cc4c1873b2.png)

**Comment by bussmann** [comment]
Version 8 is my favourite up until now

**Comment by theZiz** [comment]
> Version 8 is my favourite up until now

Yeah, the face-less versions are my favourites atm, too.

**Comment by ax3l** [comment]
First of all: epic again, Alex!

Yes, I guess we have to go face-less. Reduce your browser (ctr -) to 30% and check which logo you can still recognize. The face details are too tiny, unfortunately.

**Comment by BenjaminW3** [comment]
Depends on your display resolution. On my 4k and my 3.5k screen I still prefer the version with the face.
Should we have a small Icon only consisting of the alpaka head and small text for the cases where we do not have much place?
![alpaka](https://user-images.githubusercontent.com/8956583/46080370-10749400-c19a-11e8-88d5-b06b2aca85e6.png)

**Comment by theZiz** [comment]
> Depends on your display resolution. On my 4k and my 3.5k screen I still prefer the version with the face.
> Should we have a small Icon only consisting of the alpaka head and small text for the cases where we do not have much place?

Makes sense. I guess when we find a solution for the main banner like logo we can make an official small logo out of it like you suggested.

**Comment by theZiz** [comment]
Ah and speaking about faces. I like the face, **but** the eye is awful. So if we stay with the face, *please* someone should improve the eye. :joy:

**Comment by bussmann** [comment]
Sorry, have to disagree. One logo and only one to rule them all, good for all resolutions. If you want eyes, make a gif and make them blink, otherwise, no way.

**Comment by theZiz** [comment]
> If you want eyes, make a gif and make them blink, otherwise, no way.

![blink](https://user-images.githubusercontent.com/385145/46082234-e70a3700-c19e-11e8-8ad2-2e2971ab75b1.gif)

**Comment by tdd11235813** [comment]
I also like Benjamin's alternative logo. If I have to decide then I still would go with the version 8 to push simplicity, although the cute face will be missed. Blinking eye is too much realism for me :camel: :wink:

**Comment by ax3l** [comment]
Let's take 8 then?
Works on all resolutions (important), easy to grasp & remember, works in black & white and printed in bad quality, on 800x600 beamers with low resolution on hot summer days, and with CEOs with bad eyes.

**Comment by theZiz** [comment]
I would suggest to create a PR with the Inkscape SVG, a generic SVG (font as path) and PNG next Monday if we agree on 8.
