### ISSUE TITLE
Use libc++ instead of libstdc++ when building with clang.

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#696]
By using the gcc standard library, we can not use features which are only available within clang (e.g. coroutines). This may also be the reason why we have seen issues e.g. in #673 which have not been found in CI.

**Comment by ax3l** [comment]
Maybe we just want to add a little generic `clang` toolchain file for this to the project: https://gitlab.kitware.com/cmake/cmake/issues/18309

They can be quite small and we can also access `$ENV{VARS}`s as usual to make them flexible, example: https://github.com/conda-forge/openpmd-api-feedstock/blob/3123ede999b18ed2dba49feff220ec1e594e069b/recipe/cross-linux.cmake

**Comment by BenjaminW3** [comment]
I would like to set it outside of our CMake logic within our CI build scripts so that we can still build with both standard libraries. This should be a user setting.
Do we want to test clang with both libraries in CI (add some more jobs)?
I already started experimenting with some script changes on a local branch.

**Comment by ax3l** [comment]
Ok, that sounds like a CMake toolchain file to me. They are exactly there for short-cutting a group of arguments.
