### ISSUE TITLE
`ALPAKA_FN_ACC ` compatibility with CUDA only libraries

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#73]
@BenjaminW3 is there a reason why `ALPAKA_FN_ACC` is defined as `__device__ __host__ __forceinline__`  [see here](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/core/Common.hpp#L42)

The problem is that this definition breaks the compatibility to all non alpaka gpu libraries. 
If inside a alpaka function/kernel  which is defined as `ALPAKA_FN_ACC` a non alpaka library call is used (which is defined with `__device__`) always a compiler **error** `calling a device function from host/device` is triggered.

**Comment by psychocoderHPC** [comment]
A solotion can be to change the define to:
`#define ALPAKA_FN_ACC __device__  __forceinline__`

**Comment by BenjaminW3** [comment]
When the `__host__` attribute is removed, it would not be possible to have a kernel that is simultaneously used with CUDA and on the CPU.

**Comment by psychocoderHPC** [comment]
@BenjaminW3  You are right, this was the reason I forgot. 

The question now is, how we can solve the compatibility to extern libraries? Else we can not write specialized fast versions of a kernel for a specific hardware.

**Comment by BenjaminW3** [comment]
That is a really good question. I do not see a way to directly use such CUDA only libraries.

It might be possible to define a wrapper for each such library. This wrapper uses `ALPAKA_FN_ACC` and internally dispatches to the CUDA only version within a `__CUDA_ARCH__` ifdef. The host version does not have to be implemented as long as it is only used in a non heterogeneous CUDA only simulation.

**Comment by psychocoderHPC** [comment]
Why you are closing this issue? I think alpaka is in the current state not usable with other libraries cuda libraries.

**Comment by psychocoderHPC** [comment]
A solition for this problen can be to add an flag to alpaka called `compatibility mode` which set `ALPAKA_FN_ACC` for coda only to `__device__`

**Comment by BenjaminW3** [comment]
I have started implementing an `ALPAKA_ACC_GPU_CUDA_ONLY_MODE`. The solution depends on #100 because in such a mode where `ALPAKA_FN_ACC` is defined to `__device__` only, the other accelerators can not be built at all (because they would use OpenMP and other things within a then `__device__` only function).

**Comment by psychocoderHPC** [comment]
My idea was to change the definition of ALPAKA_FN_ACC to __device__ only if only one accelerator is defined. But than only one accelerator is supported if native cuda device only functions need to be called.

**Comment by BenjaminW3** [comment]
I had the same thought to activate this mode automatically if only the CUDA accelerator is enabled. But this would prevent somebody from enabling the CUDA accelerator, his own non CUDA accelerator and none of the other default ones.

**Comment by mxmlnkn** [comment]
Just an idea. If you want to use multiple accelerators and still want to use some CUDA-only libraries from one kernel, how about overloading the kernel, or a wrapper `__host__ __device__` function?
The overloaded function for `T_ACC = ::alpaka::acc::AccGpuCudaRt< ::alpaka::dim::DimInt<3u>, unsigned int >` would then load another library than the OpenMP version.

**Comment by psychocoderHPC** [comment]
@mxmlnkn Coult you please write down a example code. I am not sure if I understand you correct.
