### ISSUE TITLE
create simple examples

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#77]
We need to add a section with `simple` examples to our example folder.
The current examples are hard to understand for beginners.

**simple example means:**
 - only one file
 - can only use one accelerator 
 - used no extern defined helper functions but *alpaka*
 - no time messurement

**Comment by erikzenker** [comment]
I would suggest to create a 'test' folder where we put the current examples, since these examples are more integration tests than example to have a quick start. Then I would fill the example folder with a bunch of simple examples like @psychocoderHPC suggested.

**Comment by BenjaminW3** [comment]
I agree with both of you.

**Comment by BenjaminW3** [comment]
Closed because the first few examples are already merged.
