### ISSUE TITLE
alpaka kernel without templates

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#78]
It is not possible to use a alpaka kernel without templates for the `operator()` in a cuda devices.

```C++
struct Foo {
    ALPAKA_FN_ACC
    void operator()(const alpakacu::Acc& acc, const float *A, const float *B, float *C, int numElements) const
    {
        auto gridDimension = alpaka::workdiv::getWorkDiv<alpaka::Grid, alpaka::Blocks>(acc);
        ...
    }
 };
```

Compiling for a CPU device works fine.
Compiling with nvcc for cuda trigger an error:
```C++
/bigdata/hplsim/scratch/widera/alpaka/include/alpaka/workdiv/Traits.hpp(69): error: calling a __device__ function("getWorkDiv") from a __host__ __device__ function("getWorkDiv") is not allowed
          detected during:
            instantiation of "auto alpaka::workdiv::getWorkDiv<TOrigin,TUnit,TWorkDiv>(const TWorkDiv &)->alpaka::Vec<alpaka::dim::Dim<TWorkDiv>, alpaka::size::Size<TWorkDiv>> [with TOrigin=alpaka::origin::Block, TUnit=alpaka::unit::Threads, TWorkDiv=alpaka::workdiv::WorkDivCudaBuiltIn<alpaka::dim::DimInt<3UL>, alpakacu::IdxSize>]" 
(134): here
            instantiation of "auto alpaka::workdiv::traits::GetWorkDiv<TWorkDiv, alpaka::origin::Block, alpaka::unit::Threads, std::enable_if<<expression>, void>::type>::getWorkDiv(const TWorkDiv &)->alpaka::Vec<alpaka::dim::Dim<TWorkDiv::WorkDivBase>, alpaka::size::Size<TWorkDiv::WorkDivBase>> [with TWorkDiv=alpakacu::Acc]" 
(69): here
            instantiation of "auto alpaka::workdiv::getWorkDiv<TOrigin,TUnit,TWorkDiv>(const TWorkDiv &)->alpaka::Vec<alpaka::dim::Dim<TWorkDiv>, alpaka::size::Size<TWorkDiv>> [with TOrigin=alpaka::origin::Block, TUnit=alpaka::unit::Threads, TWorkDiv=alpakacu::Acc]" 
/bigdata/hplsim/scratch/widera/cudaExample/./src//main.cpp(19): here
```

The reason for the error is:
 - using `alpaka::workdiv::getWorkDiv<...>(acc)` called [this ALPAKA_FN_HOST_ACC method](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/workdiv/Traits.hpp#L64)
- in the trait method the [cuda specialized method](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/workdiv/WorkDivCudaBuiltIn.hpp#L135) is called which is a `ALPAKA_FN_ACC_CUDA_ONLY` method
- **result:** calling `ALPAKA_FN_ACC_CUDA_ONLY` function from a `ALPAKA_FN_HOST_ACC`

**Comment by psychocoderHPC** [comment]
@BenjaminW3 Might be you know why this compiles with `nvcc` if the `operator()` is templated. In general this should not compile.

**Comment by BenjaminW3** [comment]
I think the reason for this could be the two phase look-up for templates in C++.

With *CPU device* only you mean that there was no CUDA loaded and the compiler was not the nvcc?
I think if CUDA is enabled and the nvcc is used but the CUDA accelerator is not used it will equally fail but with "calling a __host__ function("getWorkDiv") from a __host__ __device__ function("getWorkDiv") is not allowed"
Could you test this, please?

**Comment by psychocoderHPC** [comment]
Yes with CPU device there is not `nvcc` used.

I have not tested the case where the kernel is only defined but used. Result is coming soon.

**Comment by ax3l** [comment]
@psychocoderHPC ping

**Comment by psychocoderHPC** [comment]
@erikzenker and me discussed how we can solve #108. A workaround can be to call a full templated `ALPAKA_FN_ACC` functor which calls the user functor.

**Comment by psychocoderHPC** [comment]
> With CPU device you mean that there was no CUDA module loaded and the compiler was not the nvcc?
> I think if CUDA is enabled and the nvcc compiler is used even so the AccGpuCuda is not used but a CPU > accelerator instead, it will equally fail but with calling a __host__ function("getWorkDiv") from a __host__ > __device__ function("getWorkDiv") is not allowed
> Could you test this, please?

@BenjaminW3 If we use the nvcc and run the example with a host accelerator all works fine.

**Comment by psychocoderHPC** [comment]
@erikzenker and me found a way to fully specialize a kernel:

The way to do it is to add a dummy template parameter
```C++
struct Foo {
    template<T_notUsed = void>
    ALPAKA_FN_ACC
    void operator()(const alpakacu::Acc& acc, const float *A, const float *B, float *C, int numElements) const
    {
        auto gridDimension = alpaka::workdiv::getWorkDiv<alpaka::Grid, alpaka::Blocks>(acc);
        ...
    }
 };
```

**Comment by BenjaminW3** [comment]
Very good finding!
This should be either added as a unit test or as an example.

**Comment by mxmlnkn** [comment]
I have this problem when trying to explicitely instantiate a kernel.
