### ISSUE TITLE
remove `alpaka::block::shared::allocArr`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#80]
Currently `ALPAKA` supports two ways to allocate static sized shared memory in a kernel `allocArr` and `allocVar` 
IMO we can remove `allocArr` because the same memory allocation can described with `alpaka::block::shared::allocVar<std::array<int,10>>`.
The problem is that `std::array` is not supported by cuda 7.0. If we ship a light implementation for static sized array with alpaka we can remove the trait for `allocArr`.

a implementation for an array can be:
```C++
template<typename T_Type, size_t T_size>
struct Array
{
    T_Type m_data[T_size];

    template<typename T_Idx>
    ALPAKA_FN_HOST_ACC const T_Type& operator[](const T_Idx idx ) const
    {
        return m_data[idx];
    }

    template<typename T_Idx>
    ALPAKA_FN_HOST_ACC T_Type& operator[](const T_Idx idx )
    {
        return m_data[idx];
    }
};
```

btw with an array we can also define easily 2D arrays:
```C++
alpaka::block::shared::allocVar<std::array<std::array<int,32>,10>>
```

**Comment by erikzenker** [comment]
After thinking a little bit about it, I like the solution :-)

**Comment by BenjaminW3** [comment]
After initial scepticism I am now convinced that this is the correct solution. However, I would prefer a native `std::array` support instead of a self developed version.

**Comment by psychocoderHPC** [comment]
I am also prefer a native std::array but it is not available in cuda. We should implenent it that it looks like a native std::array. If it is available in CUDA we can create a typedef which points to std::array.

**Comment by BenjaminW3** [comment]
Could someone check if `boost::array` is supported by CUDA instead?

**Comment by psychocoderHPC** [comment]
Not tested but it can not supported because the method prefix  __device__ is missing. see http://www.boost.org/doc/libs/1_59_0/doc/html/boost/array.html
