### ISSUE TITLE
alignment implementation

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#90]
@BenjaminW3 Why we are ship a pre-processor `ALPAKA_OPTIMAL_ALIGNMENT` macro function which based on a pure pre-processor implementation and one which based on template magic?

IMO This is code base duplication, the pre-compiler implementation looks good for me and runs with all compilers. I think there is no need for the more complex template version. Maybe there is another reason for this.

**Comment by BenjaminW3** [comment]
I favor the template version as it supports arbitrary alignments while the preprocessor version only supports the cases that are explicitly written. However, gcc and icc are not standards compliant and do not support the template version. Therefore we need the preprocessor version.

**Comment by psychocoderHPC** [comment]
There is a problem if we use on the HOST GCC and on the device NVCC. For the alignment on the HOST the pre-compiler macro is used, on the device the "template magic code" is used.
It is very hard to see if both versions generate equal alignments.
If a user create a host vector of aligned elements and copy this vector to the device the array are not byte compatible if the created alignment is not equal for both compilers (host/device).

This creates a **BUG** which is very hard to find.

**Comment by psychocoderHPC** [comment]
example for host/device byte incompatibility:
- in the current pre-compiler version of `ALPAKA_OPTIMAL_ALIGNMENT` the 8 byte alignemnt is missing

```C++
struct
{
  alignas(ALPAKA_OPTIMAL_ALIGNMENT(float[2])) float foo[2];
};

**Comment by BenjaminW3** [comment]
As you have written in #91 and described in #92, this should not be a problem because the preprocessor of the host compiler is used for host and device code. This leads to equivalent alignments and does not lead to bugs.
