### ISSUE TITLE
alignment on GPU

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#91]
~~On GPU the `ALPAKA_OPTIMAL_ALIGNMENT()` macro is used this ends with a [minimal 16byte](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/core/Align.hpp#L104-L107) alignment.~~
This results in a wrong alignment for small types and create bad ptx code with byte copies. The result of the byte copies is a big lmem (stack frame) memory footprint.

The usage of [this code](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/core/Align.hpp#L116-L124) part on gpu solves the problem.

**update:** The minimal alignment is code which is out commented and is not the problem

**Comment by BenjaminW3** [comment]
Your first link is wrong ;-)

**Comment by psychocoderHPC** [comment]
I fixed the link, I thinl my new mobile phone power connector is not so important for the community^^

**Comment by psychocoderHPC** [comment]
A second problem in the pre-copiler version is the missing [alignment to 8 byte](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/core/Align.hpp#L120-L121)

**Comment by psychocoderHPC** [comment]
List of current bug/problems:

- missing [alignment to 8 byte](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/core/Align.hpp#L120-L121)
- alignment greater than [128 byte on GPU is possible](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/core/Align.hpp#L96) but not allowed 
- the possibility of byte incompatibility between host and device is possible #90 
- the [template version of ALPAKA_OPTIMAL_ALIGNMENT](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/core/Align.hpp#L129) need lmem (looked like wrong aligned data)

**Comment by psychocoderHPC** [comment]
I am confused why `nvcc` move to the code pass `#if (BOOST_COMP_GNUC || BOOST_COMP_INTEL)` which use the pre-compiler version of `ALPAKA_OPTIMAL_ALIGNMENT`?

**Comment by BenjaminW3** [comment]
Ok. So I think the first thing to do is to add the missing 8 byte case. Could you write a PR for this?

**Comment by psychocoderHPC** [comment]
yes

**Comment by BenjaminW3** [comment]
If you are at it, could you please remove the commented out code in the template version for a minimum of 16 bytes alignment? It is only confusing us.

**Comment by BenjaminW3** [comment]
Is the lmem issue now solved with the fixes being applied?

**Comment by psychocoderHPC** [comment]
The most of it. There are some more magic 16 byte alignments with `alignas(16)` in the code. I will check if this one had negative effect.

**Comment by psychocoderHPC** [comment]
closed with #103
